/*
 * Copyright 2026 ZendTay Studio
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const a = require('assert');

const {detect, detectAll, getDatabaseInfo, supportedLanguages, languages, hasLanguage, code3, name} = require('./index');

const {tokenize: e} = require('./clear');

const n = require('./lang-name');

// Real corpus samples per language (embedded; the languages/ folder is not needed).
const i = {
    ab: 'Ауаҩытәыҩса изинқәа Зегьеицырзеиҧшу Адекларациа Алагалажәа Дызусҭзаалак, ауаатәыҩсатә ҭаацәара иалахәу иҳаҭыри, иара иузиҟәымҭхо имоу изинқәеи, ахақәиҭреи, аиашареи, адунеижәларбжьаратәи аҭынчреи шьаҭас ишрымоу хшыҩзышьҭра азуа, иара убас ауаҩы изинқәа ратәамбареи хырҩаа рымҭареи, ламыс змоу дарбанзаалак изымычҳаша агыгшәыгратә хымҩаҧгашьа аҟынӡа ауаҩы дышнанагахьо еилкааны, насгьы ауаҩы иажәеи идунеихәаҧшышьеи дрықәиҭны, ашәареи амамзаареи дыдмыргәаҟуа – адунеи иахьабалак абри аҩыза аҧсҭазаара аҧҵара ауаҩы зегь иреиҳау игәыҕрақәа ишыруакыу хшыҩзышьҭра азуа, иара убас, ауаҩы аџьамыҕәеи ахәуреи иаартны дырҿамгылар ада царҭа имамкәа аҟынӡа инамгараз, ауаҩы изинқәа азакуан амчра иамыхьчар ада ҧсыхәа шыҟам хшыҩзышьҭра азуа, иара убас ажәларқәа реиҩызара аизҳазыҕьара ацхыраара шаҭахыу хшыҩзышьҭ',
    af: 'Aanhef AANGESIEN erkenning vir die inherente waardigheid en die gelyke en onvervreembare reg van alle lede van die menslike ras die basis vir vryheid, geregtigheid en vrede in die wereld is; AANGESIEN minagting vir menseregte barbaarse dade wat die gewete van die mens aangetas het en die aanvang van ’n wereld waarin mense vryheid van spraak, geloof, vrees en behoefte het, gesien word as die hoogste aspirasie van die gemiddelde mens; AANGESIEN dit noodsaaklik is dat menseregte deur die wet beskerm word ten einde te voorkom dat mense nie gedwing gaan word om in opstand teen tirannie en onderdrukking te kom nie; AANGESIEN dit noodsaaklik is om die ontwikkeling van vriendelike bande tussen nasies aan te moedig; AANGESIEN die volke wat lid van die Verenigde Volke Organisasie is, hul geloof in f',
    am: 'ስለሰብአዊ፡መብቶች፡ለማስተማር፡ የሚረዱ፡አንዳንድ፡ዘዴዎች። በዩኔስኮ፡ተዘጋጅቶ፡በኢትዮጵያ፡ብሄራዊ፡ኮሚሽን፡ተተረጎመ አንቀጽ፡፩፤ የሰው፡ልጅ፡ሁሉ፡ሲወለድ፡ነጻና፡በክብርና፡በመብትም፡እኩልነት፡ያለው፡ነው።፡የተፈጥሮ፡ማስተዋልና፡ሕሊና፡ስላለው፡አንዱ፡ሌላውን፡በወንድማማችነት፡መንፈስ፡መመልከት፡ይገባዋል። አንቀጽ፡፪፤ እያንዳንዱ፡ሰው፡የዘር፡የቀለም፡የጾታ፡የቋንቋ፡የሃይማኖት፡የፖለቲካ፡ወይም፡የሌላ፡ዓይነት፡አስተሳሰብ፡የብሔራዊ፡ወይም፡የኀብረተሰብ፡ታሪክ፡የሀብት፡የትውልድ፡ወይም፡የሌላ፡ደረጃ፡ልዩነት፡ሳይኖሩ፡በዚሁ፡ውሳኔ፡የተዘረዘሩት፡መብቶችንና፡ነጻነቶች፡ሁሉ፡እንዲከበሩለት፡ይገባል። ከዚህም፡በተቀረ፡አንድ፡ሰው፡ከሚኖርበት፡አገር፡ወይም፡ግዛት፡የፖለቲካ፡የአገዛዝ፡ወይም፡የኢንተርናሽናል፡አቋም፡የተነሳ፡አገሩ፡ነጻም፡ሆነ፡በሞግዚትነት፡አስተዳደር፡ወይም፡እራሱን፡ችሎ፡የማይተዳደር፡አገር፡ተወላጅ፡ቢሆንም፡በማንኛውም፡ዓይነት፡ገደብ፡ያለው፡አገዛዝ፡ሥር፡ቢሆንም፡ልዩነት፡አይፈጸምበትም። አንቀጽ፡፫፤ እያንዳንዱ፡ሰው፡የመኖር፣፡በነጻነትና፡በሰላም፡የመኖሩ፡መጠበቅ፡መብት፡አለው። አንቀጽ፡፬፤ ማንም፡ሰው፡ቢሆን፡በባርነት፡አይገዛም።፡ባርነትና፡የባሪያ፡ንግድም፡በማንኛውም፡ዓይነት፡ክልክል፡ነው። አንቀጽ፡፭፤ ማንም፡ሰው፡ቢሆን፡የጭካኔ፡ስቃይ፡እንዳይደርስበት፡ወይም፡ከሰብዓዊ፡አፈጻጸም፡ውጭ፡የሆነ፡የተዋረድ፡ተግባር፡ወይም፡ቅጣት፡አይፈጸምበትም። አንቀጽ፡፮፤ እያንዳንዱ፡ሰው፡በሕግ፡ፊት፡በሰው፡ዘርነቱ፡የመታወቅ፡መብት፡አለው። አንቀ',
    ar: 'ذهبت العائلة في رحلة إلى الشاطئ في نهاية الأسبوع الماضي. كان الطقس مثالياً للسباحة والاستمتاع بأشعة الشمس طوال فترة بعد الظهر. بنى الأطفال قلاعاً من الرمال بينما كان الوالدان يسترخيان في الظل. تناولوا سمكاً طازجاً وشربوا ماء جوز الهند في المطعم المحلي. في المساء، تمشوا على طول الشاطئ يتأملون النجوم ويستمعون إلى صوت الأمواج. كان يوماً رائعاً سيتذكره الجميع إلى الأبد.',
    ay: 'AKAPACH JAQE WALINKAÑAPATAKI INOQAT ARU Qalltañataki UNANCHASA, aka pachana jaqejh munañanïsina, cheqpacha amuyasisa, cheqa thakir sarjhatasa, jilan sullkanjama arnaqasa, jan nuwasisa utjañaru wayt asiñ yati; UNANCHASA, jaqen walinkañapataki wakisir arunaka armasna, yaqhep jaqejh masinakaparu khuyañ autuyi, mututanakasti, uñatatasisa, wajcha kankañapa atipasna, jan khitirus ajhsarasa, cheq-cheqa qhana arumpi arustatasjhapjhe; UNANCHASA, jaqen walinkañapataki inoqat arujha arjhatatäñapaw jan jaqe ñanqhachirinakaru ch ajhwa qalítasna waninchapjhañapataki; UNANCHASA, taqpacha markanakajh kunti munapjhe ukanaka jikjhatañatakiejh jupanakpacha sumäñat arusthapisipjhañapaw; UNANCHASA, Mathapit Mayachat Markanakan Arupa taqjhatasna akham markanakajh amuyasi: Taqe mayniwa, chachas warmis, jaqe kank',
    az: 'Ailə keçən həftə sonu çimərliyə səyahət etdi. Hava bütün günorta üzmək və günəşlənmək üçün mükəmməl idi. Uşaqlar qum qalaları tikirdilər, valideynlər isə kölgədə istirahət edirdilər. Yerli restoranda təzə balıq yedilər və hindistan cevizi suyu içdilər. Axşam ulduzlara baxaraq və dalğaların səsini dinləyərək sahil boyunca gəzdilər. Hər kəsin əbədi olaraq xatırlayacağı gözəl bir gün idi.',
    be: '10 СНЕЖНЯ 1948 ГОДА Генеральная Асамблея Арганізацыі Абʼяднаных Нацый зацвердзіла і абвясціла Усеагульную дэкларацыю правоў чалавека, поўны тэкст якой прыведзены на гэтых старонках. Прыняўшы гэта рашэнне гістарычнага значэння, Асамблея звярнулася з заклікам да ўсіх дзяржаў‐членаў Арганізацыі абнародаваць тэкст Дэкларацыі і зрабіць усё магчымае для «яе распаўсюджвання, абвяшчэння і растлумачэння, галоўным чынам у школах і іншых навучальных установах, без адрознення, якое заснавана на палітычным статусе краін або тэрыторый». УСЕАГУЛЬНАЯ ДЭКЛАРАЦЫЯ ПРАВОЎ ЧАЛАВЕКА ПРЭАМБУЛА Прымаючы пад увагу, што прызнанне годнасці, якая ўласціва ўсім членам чалавечай сямʼі, і роўных і неадʼемных правоў іх зʼяўляецца асновай свабоды, справядлівасці і ўсеагульнага міру; і прымаючы пад увагу, што грэбаванне і п',
    bg: 'Семейството отиде на плаж миналия уикенд. Времето беше перфектно за плуване и слънчеви бани цял следобед. Децата строяха пясъчни замъци, докато родителите си почиваха на сянка. Ядоха прясна риба и пиха кокосова вода в местния ресторант. Вечерта се разхождаха по брега, гледайки звездите и слушайки звука на вълните. Беше прекрасен ден, който всички ще запомнят завинаги.',
    bi: 'Deklereisen Blong Raet Blong Evri Man Mo Woman Raon Wol FESTOK From se Jenerol Asembli i luksave respek mo ikwol raet blong man mo woman olsem stamba blong fridom, jastis mo pis long wol, From se fasin blong no luksave mo no respektem ol raet blong man mo woman i mekem se i gat ol nogud aksen i tekemples we oli mekem se pipol i kros, mo bambae wan taem i kam we pipol bambae i glad long fridom blong toktok mo biliv blong hem, fridom blong no fraet mo wantem samting hemi kamaot olsem nambawan tingting blong ol grasrut pipol, From se hemi wan impoten samting, sipos man i no fos blong lukaotem help, olsem wan las aksen we hemi save mekem, blong faet agensem rabis fasin blong spoelem no fosem pipol hemia blong mekem nomo se Loa i protektem ol raet blong man mo woman, From se i gat nid blong pro',
    bn: 'পরিবারটি গত সপ্তাহান্তে সমুদ্র সৈকতে ভ্রমণ করেছিল। বিকেল জুড়ে সাঁতার কাটা এবং রোদ পোহানোর জন্য আবহাওয়া নিখুঁত ছিল। বাচ্চারা বালির দুর্গ তৈরি করছিল যখন বাবা-মা ছায়ায় বিশ্রাম নিচ্ছিলেন। তারা স্থানীয় রেস্তোরাঁয় তাজা মাছ খেয়েছিলেন এবং নারকেল জল পান করেছিলেন। সন্ধ্যায়, তারা তারা দেখতে এবং wavesেউয়ের শব্দ শুনতে তীরে হাঁটত। এটি একটি দুর্দান্ত দিন ছিল যা সবার চিরকাল মনে থাকবে।',
    bo: '༄༅༎ ཡོངས་ཁྱབ་གསལ་བསྒྲགས་འགྲོ་བ་མིའི་ཐོབ་ཐང༌། མཐའ་དོན་གཏན་ལ་ཕབ་པའི་ཡིག་ཆ། མཉམ་སྦྲེལ་རྒྱལ་ཚོགས་ཀྱི་ཡོངས་ཁྱབ་དྲིལ་བསྒྲགས་ལས་ཁང་༎ སྔོན་བརྗོད། ༈ འགྲོ་བ་མིའི་ཁྱིམ་ཚང་ཁག་གི་ནང་མི་ཡོངས་ལ་རང་བཞིན་ཉིད་ནས་ཡོད་པའི་ཆེ་མཐོངས་དང་འདྲ་མཉམ། སུས་ཀྱང་འཕྲོག་ཏུ་མི་རུང་བའི་ཐོབ་ཐང་བཅས་ཀྱི་གནད་དོན་རྟོགས པར་བྱེད་པ་ནི། འཛམ་གླིང་ནང་གི་རང་དབང་དང༌། དྲང་བདེན། ཞི་བདེ་བཅས་ཀྱི་རྣང་གཞི་ལྟེ་བ་ཡིན། འགྲོ་བ་མིའི་ཐོབ་ཐང་ལ་སྣང་ཆུང་ཁྱད་གསོད་དང༌། དམའ་འབེབས་བྱས་པ་ལ་བརྟེན་ནས་ཀླ་ཀློའི་བྱེད་སྟངས་ཤིག་བྱུང་ཡོད་པ་སྟེ། དེ་ནི་མིའི་རིགས་ཀྱི་བསམ་ཚུལ་བཟང་པོ་དང་མི་མཐུན་པའི་གནས་ཚུལ་ཞིག་བྱུང་བ་རེད།འགྲོ་བ་མིའི་རིགས་ལ་གཏམ་བརྗོད་དང༌། དད་མོས་ཀྱི་རང་དབང་སྐུང་སྐྱོབ། དགོས་མཁོ་སྒྲུབ་པའི་རང་དབང་བཅས་ལ་ལོངས་སུ་སྤྱད་ཆོག་པའི་འཛམ་གླིང་ཞིག་འབྱུང་ཐབས་དེ་ནི་སྤྱིར་བཏང་མི་མང་ཡོངས་ཀྱི་རེ་འདོད་ཆེ་ཤོས་ཤིག་ཏུ་ངེས་པ་རྒྱ་ཁྱབ་ཡོངས་སུ་གྲགས་པ་ཡིན། སྐྱེ་བོ་དག་གིས་འུ་ཐུག་ཐབས་',
    br: 'DISKLERIADUR HOLLVEDEL GWIRIOU MAB-DEN Embannet gant ar Broadou-Unanet d’an 10 a viz Kerzu 1948 Rakger –O vezañ ma’z eo war anaout an dellezegezh enstag ouzh holl izili an denelezh hag o gwirioù par ha diwerzhus eo diazezet ar frankiz, ar reizhded hag ar peoc’h, –o vezañ ma’z eo war dizanaout ha dismegañsiñ gwirioù mab-den eo bet ganet an aktoù a varbariezh a sav koustiañs mab-den en o enep, ha ma’z eo bet embannet eo donedigezh ur bed a vo ennañ gant an dud frankiz da gomz ha da grediñ, dieubet ma vint diouzh ar spont hag an dienez, a zo mennad uhelañ mab-den, –o vezañ ma’z eo ret-holl diwall gwirioù mabden gant reolenn al lezenn evit na vefe ket rediet an dud d’en em sevel ouzh an tirantegezh hag ar gwaskerezh da rekour diwezhañ, –o vezañ ma’z eo ret-holl kas war-raok an darempredoù a vi',
    bs: 'ОПШТА ДЕКЛАРАЦИЈА О ПРАВИМА ЧОВЈЕКА УСВОЈЕНА У ГЕНЕРАЛНОЈ СКУПШТИНИ УЈЕДИЊЕНИХ НАЦИЈА 10. ДЕЦЕМБРА 1948. УВОД БУДУЂИ да су признавање урођеног достојанства и једнаких и неотуђивих права свих чланова људске обитељи темељ слободе, правде и мира у свијету, БУДУЂИ да су непоштивање и презирање права човјека имали за посљедицу акте, који су грубо вријеђали савјест човјечанства, и будуђи да је стварање свијета у којем ђе људска биђа уживати слободу говора и вјеровања и слободу од страха и несташице било проглашено као највиша тежња обичних људи, БУДУЂИ да је битно да права човјека буду заштиђена владавином права, да човјек не буде приморан да као посљедњем средству прибјегне побуни против тираније и угњетавања, БУДУЂИ да је битно да се унапређује развој пријатељских односа између народа, БУДУЂИ д',
    ca: 'La família va fer un viatge a la platja el cap de setmana passat. El temps era perfecte per nedar i prendre el sol durant tota la tarda. Els nens van construir castells de sorra mentre els pares descansaven a l\'ombra. Van menjar peix fresc i van beure aigua de coco al restaurant local. Al vespre, van caminar per la riba mirant les estrelles i escoltant el so de les onades. Va ser un dia meravellós que tothom recordarà per sempre.',
    ch: 'UNIVERSAL NA DECLARASION I DERECHO SIHA PARA I TAOTAO Preambulo Asi como i recognision pot i inherente (natural)na dignidad yan pot i pareho yan inahenable (tisina maamot) na derechon todo i membron i humano na familia guiya i fundacion i liberta, justicia yan pas gi todo i tano. Asi como i dinisatende yan i denisprecia i derecho siha para i taotao manhuyon ti civilisao na finatinas siha ni esta hasen insulta i consencian i taotao yan i finato gi tano anai taotao siha umagosa i libertad kumentos, yan hinenge yan libertad gine minanao yan minalago esta maproclama como i mas takilo na aspirasion (tinanga) i comodo (regular) na taotao siha. Asi como necesario, yangin i taotao ti para uenebliga na uespiha recurso (hinagon), como i utimo na fandiskansayan gi rebulasion contra i crueldad yan baha',
    co: 'DICHJARAZIONI UNIVIRSALI DI I DIRITTI DI L’OMU Introitu Cunsidarendu ch’ellu ci voli à ricunnoscia a dignità propria di tutti i membri di a famiglia umana è i so diritti pari ed inalienabili par ch’elli sianu fundati a libertà, a ghjustizia è a paci ind’u mondu, Cunsidarendu chì, ùn cunniscendu o sprizzendu i diritti di l’omu, si hè ghjuntu à atti barbari chì a cuscenza umana ni hè rivultata, è ch’ella hè stata chjamata a spiranza più alta di l’omu quilla di fà nascia un mondu duva elli saranu libari l’omi di parlà è di creda, libarati da u tarrori è da e miseria, Cunsidarendu ch’ella hè una primura maiò ch’elli sianu prutetti i diritti di l’omu da un guvernu di dirittu, da ch’ellu ùn sia custrettu l’omu, ghjuntu à i punti stremi, à rivultà si contru à a tirannia è l’upprissioni, Cunsidare',
    cr: 'ᐁᐢᐱᑕᐢᑲᒥᑲᐠ ᐊᐢᑭᐠ ᑭᒋ ᐃᑗᐎᐣ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐅᒋ ᑲ ᑭ ᐃᔑ ᓇᐢᑯᒧᒋᐠ ᓀᐢᑕ ᑭᒋ ᑭᒋ ᐃᑗᒋᐠ ᑭᒋ ᓇᑭᐡᑲᑐᐎ ᓇᐢᑯᒥᑐᐎᓂᐠ 217 A (III) ᑲ ᐃᑕᓯᓇᑌᐠ ᑎᐢᑭᑕᓯᓇᐃᑲᐣ ᐸᐗᑕᑭᓇᔑᐡ 10 1948 ᐁ ᐱᐳᐠ ᐸᐗᑕᑭᓇᔑᐡ 10 1948 ᑲ ᐱᐳᓂᓂᐠ ᒪᒪᐎ ᐃᑕᐢᑲᓀᓯᐎᓇ ᐁ ᒪᐗᒋ ᓇᑭᐡᑲᑐᒋᐠ ᑭ ᓇᐢᑯᒧᑐᑕᒶᐠ ᓀᐢᑕ ᑭ ᑭᒋ ᐃᑗᐗᐠ ᐁ ᐅᔑᑕᒋᐠ ᐁᐢᐱᑕᐢᑲᒥᑲᐠ ᑭᒋ ᐃᑗᐎᐣ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐅᒋ ᐁ ᒥᓯᐌᔭᐠ ᐅᑕ ᑲ ᓄᑾᐠ ᐅᑕ ᓂᐱᑌ ᐅᐅ ᐸᐢᑲᔦᑭᓂᑲᓇ, ᐅᒪ ᑲ ᐃᐡᑾ ᐃᒋᐠ ᑭᒋ ᐃᑐᑕᒧᐎᐣ ᐊᓂᑭ ᐊᐣᑕ ᑭᒋ ᓇᑭᐡᑲᑐᐎᓂᐠ ᒥᓯᐌ ᑲ ᐊᔑᑕᑭᒥᑯᓯᓂᒋ ᐸᐱᐢᑭᒋ ᑭᒋ ᐊᐢᑭᔭ ᑭᒋ ᓄᑯᑕᓂᒋ ᐅᒣᓂᐤ ᑭᒋ ᐃᑗᐎᓂᓂᐤ ᑭᒋ ᐗᓴᓶᑎᔕᐃᑲᑌᐠ ᑭᒋ ᐸᔭᑌ ᓄᑯᑕᓂᐗᐠ ᑭᒋ ᐊᔭᒥᑕᓂᐗᐠ ᓀᐢᑕ ᑭᒋ ᐸᔭᑌ ᐎᑕᒪᒋᐠ ᑭᒋᐌ ᐱᒋ ᑭᐢᑭᓄᐊᒪᑐᐎᑲᒥᑯᐠ ᓀᐢᑕ ᑯᑕᑭᔭ ᑭᐢᑭᓄᐊᒪᑐᐎᑲᒥᑾ ᐁᑲ ᑭᒋ ᑲᓇᐗᐸᒋᑲᑌᐠ ᐁᔑ ᐱᑐᔑᓇᑾᓄᑴ ᐅᑭᒪᐎᐎᐣ ᐱᒋ ᐸᐯᐢᑭᒋ ᐊᐢᑭᔭ ᓀᐢᑕ ᑯᑕᑭᔭ ᐊᐢᑭᔭ᙮ ᓂᑲᓂ ᐃᑗᐎᐣ ᐃᑕ ᐁ ᐃᔑ ᓂᓯᑕᐎᓂᒋᑲᑌᐠ ᒥᓯᐌ ᑲ ᑕᔑᐟ ᐎᒋᔕᓂᑐᐎᓂᐠ ᑭᐡᑌᓂᑕᑯᓯᐎᓂᐠ ᐁᑭ ᐃᔑ ᓂᑕᐎᑭᐟ ᓀᐢᑕ ᐊᓂᐃ ᒥᓂᑯᐎᓯᐎᓇ ᐯᔭᑾᓄᐠ ᐁ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᓀᐢᑕ ᐁᑲ ᒋᑭ ᐊᓂᐢᑫᐸᓂᓂᐠ ᐎᓇ ᐱᑯ ᑲ ᑭ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᐁᑯᑕ ᐌᒋ ᓂᐸᐎᒪᑲᐠ ᑎᐯᓂᒥᑎᓱᐎᐣ ᓀᐢᑕ ᑾᔭᐢᑭᑕᑎᓯᐎᐣ ᓀᐢᑕ ᑲᔭᒣᓂᑕᒧᐎᐣ ᐅᑕ ᐊᐢᑭᐠ᙮ ᐁᑯ ᒪᑲ ᐁᑲ ᐁ ᐱᓯᐢᑫᓂᒋᑲᑌᐠ ᓀᐢᑕ ᐁ ᐱᑯᓂᑲᑌᑭ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐁ',
    cs: 'Rodina vyrazila na pláž minulý víkend. Počasí bylo ideální pro plavání a opalování celé odpoledne. Děti stavěly hrady z písku, zatímco rodiče odpočívali ve stínu. Jedli čerstvé ryby a pili kokosovou vodu v místní restauraci. Večer se procházeli po břehu, dívali se na hvězdy a poslouchali zvuk vln. Byl to nádherný den, na který budou všichni vzpomínat navždy.',
    cy: 'Aeth y teulu ar daith i\'r traeth y penwythnos diwethaf. Roedd y tywydd yn berffaith ar gyfer nofio ac ymlacio yn yr haul drwy\'r prynhawn. Adeiladodd y plant gestyll tywod tra\'r rhieni yn ymlacio yn y cysgod. Bwytasant bysgod ffres ac yfasant ddŵr cnau coco yn y bwyty lleol. Gyda\'r nos, cerddent ar hyd y lan yn gwylio\'r sêr ac yn gwrando ar sŵn y tonnau. Roedd yn ddiwrnod hyfryd y bydd pawb yn ei gofio am byth.',
    da: 'Familien tog en tur til stranden i sidste weekend. Vejret var perfekt til svømning og solbadning hele eftermiddagen. Børnene byggede sandslotte, mens forældrene slappede af i skyggen. De spiste frisk fisk og drak kokosvand på den lokale restaurant. Om aftenen gik de langs kysten og kiggede på stjernerne og lyttede til bølgernes lyd. Det var en vidunderlig dag, som alle vil huske for evigt.',
    de: 'Die Familie machte am vergangenen Wochenende einen Ausflug an den Strand. Das Wetter war den ganzen Nachmittag perfekt zum Schwimmen und Sonnenbaden. Die Kinder bauten Sandburgen, während die Eltern sich im Schatten entspannten. Sie aßen frischen Fisch und tranken Kokoswasser im örtlichen Restaurant. Am Abend gingen sie am Ufer entlang, beobachteten die Sterne und lauschten dem Rauschen der Wellen. Es war ein wundervoller Tag, an den sich alle für immer erinnern werden.',
    dz: 'འགྲོ་བ་མིའི་དབང་ཆ་གི་འཛམ་གླིང་གསལ་བསྒྲགས། གླེང་གཞི། དེ་ཡང་ འཛམ་གླིང་ནང་གི་ཞི་བདེ་དང་དྲང་ཁྲིམས། དེ་ལས་དལ་དབང་ཚུ་གི་གཞི་འགྱམ་གཙོ་བོ་དེ་ འགྲོ་བ་མིའི་རིགས་ག་ར་དང་མཉམ་ ལྷན་ཅིག་སྐྱེས་ཏེ་ཡོད་པའི་བརྩི་མཐོང་དང་འདྲ་མཉམ། རང་དང་འབྲེལ་བ་མེད་པའི་དལ་དབང་ཚུ་ཨིན་པའི་ངོས་འཛིན་གྲུབ་ཨིན། དེ་ཡང་ འགྲོ་བ་མིའི་དལ་དབང་ལུ་ཆ་གནས་མ་འབད་མི་དང་། བརྩི་བཀུར་མ་འབད་མི་ལུ་བརྟེན་ཏེ་ ཀླ་ཀློའི་སྤྱོད་པ་དང་འབྲེལ་བའི་བྱ་སྤྱོད་ལུ་བརྩོན་བཅུག་སྟེ་ འགྲོ་བ་མིའི་རྣམ་དཔྱོད་དེ་ར་ཁོང་ཁྲོ་དང་ལྡན་མི་ཅིག་ལུ་བཟོ་སྟེ་ཡོདཔ་མ་ཚད།སྤྱིར་བཏང་འགྲོ་བ་མི་ཚུ་གིས་ རང་ར་སོ་སོའི་ ཁའི་དལ་དབང་དང་ཡིད་ཆེས་ཀྱི་དལ་དབང་། དེ་ལས་ འདྲོག་འཇིགས་མེདཔ་གཅིག་དགོ་པའི་དལ་དབང་ཚུ་ཁག་ཆེ་ཤོས་གཅིག་ལུ་འགྱུར་ཏེ་ཡོདཔ་ཨིན། དེ་ཡང་ ག་དེམ་གཅིག་འབད་ འགྲོ་བ་མི་ཚུ་གིས་ དབང་སྐྱོང་དང་དབང་གནོན་ལས་བཟློག་ཐབས་ལུ་ མཐའ་མཇུག་གི་ཐབས་ཤེས་བཟུམ་ཅིག་འབད་ ངོ་བརྒལ་འབད་དགོཔ་མེདཔ་སྦེ་བཞག་དགོ་པ་ཅིན་ འགྲོ་བ',
    el: 'Η οικογένεια πήγε εκδρομή στην παραλία το περασμένο σαββατοκύριακο. Ο καιρός ήταν τέλειος για κολύμπι και ηλιοθεραπεία όλο το απόγευμα. Τα παιδιά έχτισαν κάστρα από άμμο ενώ οι γονείς χαλάρωναν στη σκιά. Έφαγαν φρέσκο ψάρι και ήπιαν νερό καρύδας στο τοπικό εστιατόριο. Το βράδυ, περπάτησαν κατά μήκος της ακτής κοιτάζοντας τα αστέρια και ακούγοντας τον ήχο των κυμάτων. Ήταν μια υπέροχη μέρα που όλοι θα θυμούνται για πάντα.',
    en: 'The family went on a trip to the beach last weekend. The weather was perfect for swimming and sunbathing all afternoon. The children built sandcastles while the parents relaxed in the shade. They ate fresh fish and drank coconut water at the local restaurant. In the evening, they walked along the shore watching the stars and listening to the sound of the waves. It was a wonderful day that everyone will remember forever.',
    eo: 'Universala Deklaracio de Homaj Rajtoj Adoptita kaj proklamita de Rezolucio 217 A (III) de la Ĝenerala Asembleo, 10an de decembro 1948 Antaŭkonsideroj Pro tio, ke agnosko de la esenca digno kaj de la egalaj kaj nefordoneblaj rajtoj de ĉiuj membroj de la homara familio estas la fundamento de libero, justo kaj paco en la mondo, Pro tio, ke malagnosko kaj malestimo de la homaj rajtoj rezultigis barbarajn agojn, kiuj forte ofendis la konsciencon de la homaro, kaj ke la efektiviĝo de tia mondo, en kiu la homoj ĝuos liberecon de parolo kaj de kredo kaj liberiĝon el timo kaj bezono, estas proklamita kiel la plej alta aspiro de ordinaraj homoj, Pro tio, ke nepre necesas, se la homoj ne estu devigitaj, sen alia elektebla vojo, ribeli kontraŭ tiranismo kaj subpremo, ke la homaj rajtoj estu protektata',
    es: 'La familia salió de viaje hacia la playa el fin de semana pasado. El clima estaba perfecto para nadar y tomar el sol durante toda la tarde. Los niños construyeron castillos de arena mientras los padres descansaban en la sombra. Comieron pescado fresco y bebieron agua de coco en el restaurante del lugar. Por la noche, caminaron por la orilla viendo las estrellas y escuchando el sonido de las olas. Fue un día maravilloso que todos recordarán por siempre.',
    et: 'Perekond sõitis eelmisel nädalavahetusel rannareisile. Ilm oli suurepärane ujumiseks ja päevitamiseks terve pärastlõuna. Lapsed ehitasid liivalosse, samal ajal kui vanemad puhkasid varjus. Nad sõid värsket kala ja jõid kookosvett kohalikus restoranis. Õhtul kõndisid nad mööda kallast, vaadates tähti ja kuulates lainete häält. See oli imeline päev, mida kõik mäletavad igavesti.',
    eu: 'GIZA ESKUBIDEEN ALDARRIKAPEN UNIBERTSALA HITZAURREA Kontuan izanik munduko askatasuna, justizia eta bakea giza familiako kide guztien berezko duintasunean eta eskubide berdin eta ukaezinetan oinarritzen direla; Kontuan izanik giza eskubideak ez ezagutzearen eta gutxiestearen ondorioz, giza kontzientziari irain egiten dioten basakeriak gertatu izan direla; eta gizon-emakumeek, beldur eta gabezia orotik aske, hitz egiteko askatasuna eta sinesmen-askatasuna izango dituzten munduaren etorrera aldarrikatu dela gizakiaren helburu nagusi; Kontuan izanik ezinbestekoa dela giza eskubideak zuzenbidezko erregimen batek babestea, gizakia-tirania eta zapalkuntzaren aurkako azken irtenbidea den matxinadara jo beharrean aurkitu ez dadin; Kontuan izanik ezinbestekoa dela, baita ere, herrialdeen artean har',
    fa: 'اعلامیه جهانی حقوق بشر مصوب دهم دسمبر ۱۹۴۸ میلادی از جانب مجمع عمومی سازمان ملل مقدمه از آنجا که شناسائی حیثیت ذاتی کلیهٔ اعضای خانواده بشری و حقوق یکسان و انتقال ناپذیر آنان اساس آزادی و عدالت و صلح را در جهان تشکیل میدهد، از آنجا که عدم شناسائی و تحقیر حقوق بشر منجر به اعمال وحشیانه‌یی گردیده است که روح بشریت را به عصیان واداشته و ظهور دنیایی که در آن افراد بشر در بیان و عقیده آزاد و از ترس و فقر فارغ باشند بعنوان بالاترین آمال بشر اعلام شده است، از آنجا که اساساً حقوق انسانی را باید با اجرای قانون حمایت کرد تا بشر به عنوان آخرین علاج به قیام بر ضد ظلم و فشار مجبور نگردد، از آنجا که اساساً لازم است توسعه روابط دوستانه بین ملل را مورد تشویق قرار داد، از آنجا که مردم ملل متحد باور خود را بحقوق اساسی بشر و مقام و ارزش فرد انسانی و تساوی حقوق مرد و زن مجدداً در منشور اعلام کرده‌اند و تصمیم ر',
    fi: 'Perhe teki matkan rannalle viime viikonloppuna. Sää oli täydellinen uimiseen ja auringonottoon koko iltapäivän. Lapset rakensivat hiekkalinnoja, kun vanhemmat lepäsivät varjossa. He söivät tuoretta kalaa ja joivat kookosvettä paikallisessa ravintolassa. Illalla he kävelivät rannalla tähtiä katsellen ja aaltojen ääntä kuunnellen. Se oli ihana päivä, jonka kaikki muistavat ikuisesti.',
    fj: 'LAWA RARABA NI DODONU NI LEWENIVANUA Ena 10 ni Tiseba 1948, a vakadonuya qai kacivaka na Vale ni Bose Levu ni Matabose Levu kei vuravura na Lawa Raraba ni Dodonu ni Lewenivanua. Sa volai tiko yani oqo na lewe ni Lawa. Ena toqai ena itukutuku ni veigauna na lawa oqo, ni vakadonui oti, era uqeti sara na lewe ni Matabose mera kucivaka ra qai “raica me kaburaki, vakaraitaki, wiliki qai vakamacalataki, vakauasivi e veikoronivuli kei na veitabana cava tale ni vuli. Me kua sara ni caka oqo ena dela ni veivakaduiduitaki ena vuku ni itutu vakapolitiki ni dua na vanua se vanua tu vakataki koya se vanua qali.” IKAU Ni yavu ni galala, lewa dodonu kei na sautu ena vuravura na noda vakadinata ni dodonu mera dokai mera raici tale ga vakatautauvata na lewe kece ga ni vuvale kawatamata, Ni na tubu na itovo',
    fo: 'HEIMSYVIRLÝSING UM MANNARÆTTINDI INNGANGUR Tað verður at viðurkenna, at menniskjuni er virðing íborin, og at allir limir mannaættarinnar eiga somu ómissiligu rættindi, og hetta er støðið undir frælsi, rættvísi og friði í heiminum. Har sum mannarættindini hava verið fyri vanbýti og vanvirðing, hevur tað havt við sær ræðuligar gerðir, sum hava skakað samvitsku mannaættarinnar, og ein heimskipan, har sum fólk nýtur talu- og trúarfrælsi og frælsi frá ótta og neyð, hevur verið boðað sum menniskjunar hægsta mið og mál. Tað varðar almikið um, mannarættindi verða vard við lógum, um fólk ikki skal verða noytt til sum evstu ráð at taka til uppreistur móti harðræði og kúgan. Tað varðar almikið um at elva og stimbra vinalag tióðanna millum. Í sáttmáala sínum hava Sameindu Tjóðirnar av nýggjum váttað tr',
    fr: 'La famille est partie en voyage à la plage le week-end dernier. Le temps était parfait pour se baigner et bronzer tout l\'après-midi. Les enfants ont construit des châteaux de sable pendant que les parents se reposaient à l\'ombre. Ils ont mangé du poisson frais et bu de l\'eau de coco au restaurant local. Le soir, ils se sont promenés le long du rivage en regardant les étoiles et en écoutant le bruit des vagues. Ce fut une merveilleuse journée que tout le monde se souviendra pour toujours.',
    fy: 'Universele ferklearring fan de rjochten fan de minske Universele ferklearring fan de rjochten fan de minske, proklamearre op 10 desimber 1948 troch de Algemiene Gearkomste fan e Feriene Naasjes. Pree-ambule Yn betinken nommen dat it erkennen fan de ynherinte weardichheid en fan de gelikense en ûnferfrjemdbere rjochten fan alle leden fan de minskemienskip grûnslach is foar de frijheid, rjochtfeardigens en frede yn e wrâld; Yn betinken nommen dat it oan e kant skowen en lytsachtsjen fan e rjochten fan e minske laat hawwe ta barbaarske dieden, dy t it gewisse fan it minskdorn faksearre hawwe en dat de komst fan in wrâld dêr t minsken frijheid fan mieningsutering en leauwe barre mei, en hja frij wêze sille fan eangst en ferlet, ferkundige is as it heechste ideaal fan elk minske; Yn betinken nom',
    ga: 'Chuaigh an teaghlach ar thuras go dtí an trá an deireadh seachtaine seo caite. Bhí an aimsir foirfe do snámh agus do dheamhas gréine i rith an tráthnóna. Thóg na páistí caisleáin ghainimh agus na tuismitheoirí ag scíth a ligean sa scáth. D\'ith siad iasc úr agus d\'ól siad uisce cnó cócó sa bhialann áitiúil. Tráthnóna, shiúil siad cois chladach ag breathnú ar na réaltaí agus ag éisteacht le fuaim na dtonnta. Lá iontach a bheidh i gcuimhne ag gach duine go deo.',
    gd: 'Teacs Ughdarrasail na Iomlanachd DUTHCHANNAN AONAICHTE OIFIS AN FHIOSRACHAIDH PHOBLAICH GAIRM CHOITCHEANN AIR COIRICHEAN A CHINNE-DAONNA ROI-RADH Do bhrìgh s gu bheil e air aideachadh gu bheil dualchas nàdarra agus còirichean neo-sgaraichte uile bhuill a chinne-daonna na stèidh airson saorsa, ceartas agus sìth an t-saoghail, Do bhrìgh s gun do dh adhbharaich a bhith a cur còirichean dhaoine ann an suarachas gnìomhan borba a shàraich cogaisean, a bhith air an cleachdadh, agus gum bheil an latha air teachd anns am bi saor-labhartas, saor chreideamh agus saorsa bho eagal agus dìth air a ghairm mar àrd-mhiann an t-sluaigh choitcheann, Do bhrìgh s gu bheil e uile do-sheachanta feumail - mas e nach bi an duine air a cho-èigneachadh mu dheireadh gu ceannairc a dhèanamh an aghaidh ain-tighearnas a',
    gl: 'Declaración Universal dos Dereitos das Persoas Preámbulo A liberdade, a xustiza e a paz no mundo teñen por base o recoñecemento da dignidade intrínseca e dos dereitos iguais e inalienables de tódolos membros da familia humana; O descoñecemento e o menosprezo dos dereitos da persoa orixinaron actos de barbarie aldraxantes para a conciencia da humanidade; proclamouse, como a aspiración máis elevada da persoa, o advento dun mundo no que os seres humanos, liberados do temor e da miseria, disfruten da liberdade de palabra e da liberdade de crenzas; Esencial que os dereitos da persoa sexan protexidos por un ríxime de dereito, co fin de que a persoa non se vexa compelida ó supremo recurso da rebelión contra a tiranía e a opresión; Tamén esencial promover o desenvolvemento de relacións amigables e',
    gn: 'TEKOVE YVYPORA KUERA MAYMAYVA DERECHO KUAAUKAHA Preamble (preamble missing) Art. 1 Mayma yvypóra ou ko yvy ári iñapytlʼyre ha eteĩcha dignidad ha derecho jeguerekópe; ha ikatu rupi oikuaa añetéva ha añeteʼyva, iporãva ha ivaíva, tekotevẽ pehenguéicha oiko oñondivekuéra. Art. 2 Mayma yuypóra oguereko derecho ha libertad kuéra ko Declaraciónpe oĩva, oñemañaʼyre mbaʼeichaguapa i-ráza, ipire color; kiñápa terãpa kuimbaʼe, iñeʼẽ, i-religión, iñopinión política, hetã, haʼépa mbaʼ rerekoha, oĩpa yvate terãpa nahániri sociedad ryepype, hambaʼe. Mbaʼeveichagua jeporavo avei ndoiók vaʼerã oñemañanguévo hetã situación rehe, legalmentepa mbaʼéicha oĩ, haʼépa isãsopyre, oguatáva ojeheguiete, térãpa oĩ ambue tetã ndiv térã ipoguype. Art. 3 Mayma tapicha oguereko derecho oikovévo, piporúvo ilibertad ha oj',
    gu: 'માનવ અધિકારોની વિશ્વવ્યાપી ઘોષણા પ્રારુતાવિક કેમ કે માનવકુટુંબના દરેક સભ્યની પરંપરા-પ્રાપ્ત પ્રતિષ્ઠાને અને સમાન અને અસંકામ્ય અધિકારોને માન્યતા આપવી એ જગતની સ્વતંત્રતા, ન્યાય અને શાંતિનો પાયા છે, કેમ કે માનવ અધિકારોની ઉપેક્ષા અને અપમાન કરવાથી એવાં જંગલી કત્યો પરિણમ્યાં છે કે જેણે માનવજાતના અંતઃકરણમાં બળવો જગવ્યો છે અને સામાન્ય લોકોની ઊંચામાં ઊંચી મહત્ત્વાકાંક્ષા તરીકે એવી દુનિયાના આગમનની જાહેરાત કરવામાં આવી છે, જેમાં માનવો વાણી અને વિચારની સ્વતંત્રતા ભોગવશે અને ભય તથા અછતમાંથી મુકિત મેળવશે, કેમ કે જો માણસને આખરી ઉપાય તરીકે જુલમ અને અત્યાચાર સામે બળવો પોકારવાનો આશ્રય લેવાનું દબાણ કરાવવું ન હોય તો કાયદાની સત્તા દ્વારા માનવ અધિકારોને રક્ષણ આપવું જોઇએ, કેમ કે રાષ્ટ્રો વચ્ચે મૈત્રીસંબંધોનો વિકાસ બઢાવવાનું જરૂરી છે, કેમ કે સંયુકત રાષ્ટ્રોના લોકોએ ખતપત્રમાં મૂળભૂત માનવ અધિકારોમાં માનવીની પ્રતિષ્ઠ',
    ha: 'JEŊJEŊ KPAŊMƆ NI KƆƆ GBƆMƆ ADESA HEGBƐI AHE MLIBOTEMƆ Akɛni aŋɔɔ nɔ akɛ afɔ gbɔmɛi adesai fɛɛ akɛ mɛi ni yeɔ egbɔ kɛ heyeli ko ni anyɛŋ ashɔ̃ yɛ amɛdɛŋ, ni nomɛi ji heyeli, jalɛsane kɛ toiŋjɔlɛ shishifãi yɛ je lɛ mli hewɔ lɛ, Akɛni bu ni abuuu, kɛ asaŋ gbɔmɔ adesa hegbɛi anɔ ni anaanaa yɛ shikpɔŋ lɛ etsɔ gbɔmɔ yitsoŋ ni eha efeɔ yiwalɛ nii, kɛ amrɔ nɛɛ gbɛgbelemɔ akɛ mɛi foji anine ashɛ amɛshweenii anɔ bɔ ni amɛaanyɛ amɛwie nɔ ni amɛsusuɔ yɛ nɔ ko he, amɛhe nɔ ni amɛsusuɔ akɛ eja gbɛ pɛ amɛye, akanyɛ awo amɛhe gbeyei dɔŋŋ, ni asaŋ akakama amɛ nɔ ko nɔ ko hewɔ lɛ, Akɛni suɔmɔ ni asumɔɔɔ akɛ atsɔɔ gbɛ kroko nɔ ajieɔ yiwalɛ nɔyeli ko hewɔ ni ehiaa akɛ awo mla ni baafã gbɔmɔ adesa hegbɛi ahe hewɔ lɛ, Akɛni ehe hiaa akɛ akã he aha naanyobɔɔ ahi maji ateŋ hewɔ lɛ, Akɛni mɛi ni yɔɔ Jeŋmaji Eko',
    he: 'המשפחה יצאה לטיול לחוף הים בסוף השבוע שעבר. מזג האוויר היה מושלם לשחייה ולשיזוף לאורך כל אחר הצהריים. הילדים בנו טירות חול בזמן שההורים נחו בצל. הם אכלו דגים טריים ושתו מי קוקוס במסעדה המקומית. בערב, הם טיילו לאורך החוף תוך התבוננות בכוכבים והאזנה לקול הגלים. זה היה יום נפלא שכולם יזכרו לנצח.',
    hi: 'परिवार पिछले सप्ताहांत समुद्र तट की यात्रा पर गया था। दोपहर भर तैराकी और धूप सेंकने के लिए मौसम एकदम सही था। बच्चों ने रेत के महल बनाए जबकि माता-पिता छाया में आराम कर रहे थे। उन्होंने स्थानीय रेस्तरां में ताज़ी मछली खाई और नारियल पानी पिया। शाम को, वे तारों को देखते हुए और लहरों की आवाज़ सुनते हुए किनारे पर टहले। यह एक अद्भुत दिन था जिसे हर कोई हमेशा याद रखेगा।',
    hr: 'Obitelj je otputovala na plažu prošlog vikenda. Vrijeme je bilo savršeno za plivanje i sunčanje cijelo poslijepodne. Djeca su gradila dvorce od pijeska dok su se roditelji opuštali u hladu. Jeli su svježu ribu i pili kokosovu vodu u lokalnom restoranu. Navečer su šetali uz obalu gledajući zvijezde i slušajući zvuk valova. Bio je to prekrasan dan kojeg će se svi zauvijek sjećati.',
    hu: 'A család kirándult a tengerpartra a múlt hétvégén. Az idő tökéletes volt úszáshoz és napozáshoz egész délután. A gyerekek homokvárat építettek, míg a szülők a árnyékban pihentek. Friss halat ettek és kókuszvizet ittak a helyi étteremben. Este a part mentén sétáltak, csillagokat nézve és a hullámok hangját hallgatva. Csodálatos nap volt, amit mindenki örökké emlékezetesnek fog tartani.',
    hy: 'Ընտանիքը վերջին շաբաթավերջին ճանապարհորդեց դեպի լողափ: Եղանակը կատարյալ էր լողալու և արևայրուք ընդունելու համար ամբողջ կեսօրին: Երեխաները ավազից ամրոցներ էին կառուցում, մինչ ծնողները հանգստանում էին ստվերում: Նրանք տեղական ռեստորանում թարմ ձուկ կերան և կոկոսի ջուր խմեցին: Երեկոյան նրանք քայլում էին ափով՝ նայելով աստղերին և լսելով ալիքների ձայնը: Դա հրաշալի օր էր, որը բոլորը հավերժ կհիշեն:',
    ia: 'DECLARATION UNIVERSAL DEL DERECTOS HUMAN PREAMBULO Considerante que le recognoscentia del dignitate inherente a tote le membros del familia human e de lor derectos equal e inalienabile constitue le fundamento del libertate, del justitia e del pace in le mundo, Considerante que le ignorantia e le disprecio del derectos human ha resultate in actos de barbaria que ultragia le conscientia del humanitate, e que le advenimento de un mundo in le qual le esseres human essera libere de parlar e de creder, liberate del terror e del miseria, ha essite proclamate como le plus alte aspiration del homine, Considerante que il es essential que le derectos human es protegite per medio de un regime de derecto, a fin que le homine non es compellite al ultime recurso del rebellion contra le tyrannia e le oppr',
    id: 'Keluarga melakukan perjalanan ke pantai akhir pekan lalu. Cuaca sangat sempurna untuk berenang dan berjemur sepanjang sore. Anak-anak membangun istana pasir sementara orang tua bersantai di tempat teduh. Mereka makan ikan segar dan minum air kelapa di restoran lokal. Di malam hari, mereka berjalan di sepanjang pantai sambil melihat bintang dan mendengarkan suara ombak. Itu adalah hari yang indah yang akan dikenang semua orang selamanya.',
    ig: 'NKUWUWAPỤTA ỤWA NILE BANYERE IKIKE MMADỤ NWEGASỊRỊ Okwu mmalite Ebe ọ bụ na nghọta ugwu ekere uwa na ikike nha anya a pụghị ịnapụ mmadụ nke dirị onye ọ bụla bi n ụwa bụ ntụala nke inwere onwe, ikpe nkwụmọtọ na udo n elụ ụwa. Ebe nleghara anya na nleli ikike mmadu nwegasịrị emeela ka e nwee akparamagwa enweghi uche nke gbawara obi mmadụ nile, a bịakwa ọbịbịa ụwa ebe ndi mmadụ ga‐enwejupụta ohere ikwu okwu na inwe nkwenye nakwa nlihapụ n ụjọ na ụkọ, abụrụ ihe a mara n okwa dị ka olile anya kachasị ibe ya nke mmadụ nkịtị. Ebe ọ dị mkpa, ma ọ bụrụ na a chọghi ikwanye mmadụ ka o were oke nnupu isi sogide ochịchị aka ike na mmegbu dị ka ihe ikpeazụ ọ pụrụ ime, na a ga‐echedo ikike mmadụ nwegasịrị site n usoro iwu. Ebe ọ dị mkpa ịkwalite ọganihu mmekọrịta enyi na enyi n etiti mba na ibe ya. Ebe nd',
    io: 'Universal Deklaro di Homal Yuri Adoptita e proklamita per rezolvuro 217 A (III) dil Asemblo General di 10ma decembro 1948 Introdukto Konsiderante ke agnosko dil inheranta digneso e dil egala e netransferebla yuri di omna membri di la familio homal es la fundamento di libereso, yusteso e paco en la mondo, Konsiderante ke desegardo e desestimo di homal yuri rezultabas en barbara agi, qui insultis la koncienco di la homaro, e l arivo di mondo en qua homi posedas libereso di parolo e kredo e libereso de timo e bezono esabas proklamata kom la maxim alta aspiro di la homi, Konsiderante ke oportas, por ke la homi ne esez koaktata rekursar, kom lasta posibleso, a rebeleso kontre tiraneso ed opreso, ke homal yuri devas esar protektata per la regno di la yuro, Konsiderante ke oportas avancigar la de',
    is: 'Fjölskyldan fór í ferð til strandarinnar um síðustu helgi. Veðrið var fullkomið fyrir sund og sólbað alla síðdegistímann. Börnin smíðuðu sandkastala á meðan foreldrarnir slökuðu í skugganum. Þeir borðuðu ferskan fisk og drukku kókosvatn á veitingastaðnum á staðnum. Á kvöldin gengu þeir með ströndinni horfandi á stjörnurnar og hlýðandi á hljóð öldurnar. Það var dásamlegur dagur sem allir munu muna að eilífu.',
    it: 'La famiglia ha fatto un viaggio in spiaggia lo scorso fine settimana. Il tempo era perfetto per nuotare e prendere il sole per tutto il pomeriggio. I bambini hanno costruito castelli di sabbia mentre i genitori si rilassavano all\'ombra. Hanno mangiato pesce fresco e bevuto acqua di cocco al ristorante locale. La sera, hanno camminato lungo la riva guardando le stelle e ascoltando il suono delle onde. È stata una giornata meravigliosa che tutti ricorderanno per sempre.',
    iu: 'ᓯᓚᕐᔪᐊᕐᒥᐅᑦ ᓇᓗᓇᐃᖅᓯᐅᑎᖓ ᑭᓇᒃᑯᑐᐃᓐᓇᐃᑦ ᐱᔪᓐᓇᐅᑎᖏᑦ ᑎᓯᐱᕆ 10, 1948 ᑲᑎᕐᔪᐊᕐᓂᕐᒥ ᑲᑐᔾᔨᔨᐅᔪᑦ ᓯᓚᕐᔪᐊᕐᒥᐅᓄᑦ ᐊᑐᓂᖅᑎᑦᑎᓯᒪᓂᐊᑦ ᐊᒻᒪᓗ ᐱᑖᕈᑎᖃᕐᓯᒪᓂᐅᓂᑯ ᓯᓚᕐᔪᐊᕐᒥᐅᑦ ᓇᓗᓇᐃᖅᓯᐅᑎᖓᓂᒃ ᑭᓇᒃᑯᑐᐃᓐᓇᕐᓄᑦ ᐱᔪᓐᓇᐅᑎᖏᓐᓂᒃ ᑕᒪᒃᑭᑦᑎᐊᑦᑐᒥᒃ ᑎᑎᕋᕐᓯᒪᐅᑎᖃᕐᑎᓪᓗᒍ ᓴᖅᑭᑕᐅᓯᒪᓂᑯᑦ ᑭᖕᒍᓪᓕᕇᒃᖢᑎᒃ ᒪᒃᐱᖅᑐᕋᓕᐅᕐᓯᒪᕗᑦ. ᑭᖕᒋᓪᓕᕇᖕᒋᓐᓂ ᑕᒪᑐᒧᖕᒐ ᐅᓂᒃᑲᐅᓯᖕᒐᑕ ᐱᖁᔭᓕᐊᖕᒍᒪᓂᑯ ᑲᑎᒪᑦᔪᐊᖅᑐᓂ ᖃᐃᖅᑯᔭᐅᓯᒪᓂᑰᑎᓪᓗᒋᑦ ᐃᓚᒋᔭᐅᔪᑦ ᓄᓇᖃᑎᒌᙱᑦᑐᕐᔪᐊᓂᑦ ᐅᖃᓕᒫᒐᓕᐅᓚᐅᕐᓯᒪᖕᒪᑕ ᑎᑎᕋᕐᓯᒪᔪᖕᒋᓐᓂᒃ ᓇᓗᓇᐃᖅᓯᐅᑎᖕᒐ ᐊᒻᒪᓗ ᐱᔾᔪᑎᖕᒐᓄᑦ ᓴᐃᒪᖅᑕᐅᓂᖃᖅᑎᑕᐅᖃᓪᓗᒍ, ᑕᑯᖁᔾᔨᔾᔪᑕᐅᖁᓪᓗᒍᓗ, ᐅᖃᓕᒫᑦᓂᒃᑯᑦ ᐊᒻᒪᓗ ᓇᓂᑐᐃᓐᓇᓕᖁᓪᓗᒍ ᑐᕌᖕᒐᓂᖃᑦᓗᑎᒃ ᐃᓪᓐᓂᐊᕐᕙᒃᑎᒍᑦ ᐊᒻᒪᓗ ᐊᓯᖕᒋᑎᒎᖕᒐᔪᒃᑯᑦ ᐃᓕᓐᓂᐊᖅᑐᓕᕆᓂᕐᒧᑦ ᐃᑲᔪᖅᑐᐃᕕᐅᔪᓂ, ᓴᖅᑭᑎᕆᐅᑎᑐᐃᓐᓇᐅᓇᓂ ᒐᕙᒪᓕᕆᐅᑎᒃ ᑎᑎᕋᖁᑎᒋᕙᑕᖕᒋᓐᓇ ᓄᓇᖅᑲᑎᒌᑦᑐᕐᔪᐊᑦ ᐅᕝᕙᓘᓐᓃᑦ ᓄᓇᑦᑎᐊᕐᒥᐅᓂ. ᓯᕗᓪᓕᖅ ᓇᓗᓇᐃᔭᐃᓯᒪᔪᖅ ᐃᒪᐃᒻᒪᑦ ᐃᓕᑕᖅᓯᒪᐅᑎᖃᑦᒪᑦ ᓯᕗᓕᕐᓂᓴᑐᖃᕐᓂᒃ ᓂᕐᓱᐃᓂᑦᒥᒃ ᐊᒻᒪᓗ ᐊᔾᔨᒌᒃᑎᑦᑎᓂᕐᒥᒃ ᐊᒻᒪᓗ ᐊᔪᙱᔾᔪᑕᐅᔪᓐᓇᖅᑐᓄᑦ ᐱᔪᓐᓇᐅᑎᓂᒃ ᑕᒪᐃᓐᓄᓕᒫᑦᑎᐊᖅ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑕᒪᒃᑯᐊ ᐃᓈᔪᑦ ᐃᓚᒌᒍᓯᖕᒋᑎᒍᑦ ᑐᙵᕕᐅᓪᓚᕆᖕᒪᑦ ᐃᓱᒪᖅᓱᕐᓂᖅ, ᖃᓄᖕᒐᓴᖅᑕᐅᖕᒋᓐᓂᖅ ᐊᒻᒪᓗ ᓴᐃᓕᒪᓂᖃᕐᓂᖅ ᓯᓚᕐᔪᐊᕐᒥ, ᐃᒪᐃᒻᒪᑦ ᓱᖁᑎᒋᓇᒍ ᐊᒻᒪᓗ ᓈᓚᖕᓂᕐᓗᖕᓂᖅ ᐃᓅᔪ',
    ja: '先週末、家族でビーチに旅行に行きました。天気は完璧で、午後中ずっと泳いだり日光浴をしたりして過ごしました。子どもたちは砂の城を作り、両親は日陰でリラックスしていました。地元のレストランで新鮮な魚を食べ、ココナッツウォーターを飲みました。夕方には、星を眺めながら波の音を聞きつつ海岸を散歩しました。誰もが永遠に覚えている素晴らしい一日でした。',
    jv: 'Saben umat manungsa lair kanthi hak-hak kang podho lan pinasthi lan kanthi kabebasan-kabebasan ing bakuning angger-angger (wewaton = undang-undang). Perserikatan Bangsa-Bangsa darbe komitmen (tekad nglaksanakake maujude janji lan kasaguhane) kanggo junjung luhur, nggrengsengake lan ngayomi hak-hak asasi umat manungsa marang saben pribadi (individu). Komitmen kasebut ingayatan saka Piagam Perserikatan Bangsa-Bangsa kang nukulake kamantepaning kayakinan para bangsa sa-donya tumrap hak-hak asasi umat manungsa ing bakuning paugeran sarta tumrap martabat lan ajining kamanungsan. Ing Pranyatan Umum ngenani Hak-Hak (umat) Manungsa, Perserikatan Bangsa-Bangsa nandhesake kanthi terwoco lan prasoja, hak-hak kang dadi darbeke saben uwong kanthi adil. Hak-hak kasebut, nyata dadi darbekmu kabeh. Kabeh m',
    ka: 'ოჯახი გასულ შაბათ-კვირას სანაპიროზე გაემგზავრა. ამინდი მთელი შუადღის განმავლობაში ცურვისა და მზის აბაზანებისთვის იდეალური იყო. ბავშვები ქვიშის ციხეებს აშენებდნენ, სანამ მშობლები ჩრდილში ისვენებდნენ. მათ ადგილობრივ რესტორანში ახალი თევზი მიირთვეს და ქოქოსის წყალი დალიეს. საღამოს ისინი ნაპირზე დადიოდნენ, ვარსკვლავებს უყურებდნენ და ტალღების ხმას უსმენდნენ. ეს იყო შესანიშნავი დღე, რომელსაც ყველა სამუდამოდ დაიმახსოვრებს.',
    kg: 'ya tanu kulonguka lukutakanu nzozulu glégwalè langi tadilaka central kuzola kalunga kukabula mezabanaka ca tendulaka lendongolia africaine kalemie sacré bantotila kulutisa fratrie uwele mukidi mukubu mines zengaka kyoto rep sida magazine médaille crise latini abako abuja ranque sao mecklenburg châteauroux publius martial commissaire richard kukana leganet hygiène lwangu nkoi yunnan futur prata świnoujście so thiet marek dideso operasio doors anthony léonie tombukaka fec kuyambula lex mowa rue bapoint boyomainfo soficom mozart mesimbama nikola kankindi somifor njia bicangul hlanu wayi kotala 北京市 sìchuān study locals ngungudi ńtì ouate fang bantú cassola youlou membro bibuku niue pori barca yeguas camulac kartverket monstereophonic tukala kukindiza кукабарра kifwanisi tchikapika tegel konakry оксана dateformat must anthus giallo etruscus kivandagu grosser safar tinimbang kindibu openfl dare equity lolemba pounds karaté bidia bambula babengaka vakwavo kolεmba isadora contraction sildes kewaka linventeur yeke kukipesaka datcha pairs ngblimbo capriccio padmpme geopolismagazine explorateurs wikiquote mutumekaka ágioi kiafilwanga mokonzi salongo balako melia vysakh kabengele bamaladi papers qaïda parviendront cables vitale yufulaka investit provinceorientale lumière dernier sbp courrierinternational promet nkoyi abonnement kompa fgp héritage febwandi cora luzutusu bamefundila bitezo pubid database urgences qualité asante marlene calcutta misionere violence virgile kusonikaka delépin',
    kk: 'мен де болды екен пе білемін бер көп юбаба келіп келмейді аласың әкем тамаша көрген зат болдың айта ер жер кедей өзімнің тұрыңыз болғандықтан тұра кетемін бірнеше бізбен біртүрлі көрдіңіз із дедім атап келіңдер зоодүкен дзэниба дәрігері бастап көрсеткім түсімде болмасын келмейтін ойыңды өкпе әңгіменің туфлиім ет дәрісін агенттің қауіпті түсірдім аламын алам келіпсіз емессің күт ұлым угандықтар еттім қалауың ингрид шығарсыз тексеруге үйіне жеңемін қаласыз өмірім жерім жағыңдар шақырдым қабатты жойылғаны кіріңдер шашыңды кітаптап ояндың досы шақырды ұмытты ашығып сыбайлас жазым жеткізу шиеленітпе рэнди шығардың атадан жазылды күйеді өкпенің ішінен білмеппіз вашингтоннан қымбат хабарлас шешуге тізімі жинағанға жаңалық шомылатын ұқсайтын көңілдеріңді болғанымыз итнимен мүгедектер аңшылауға ақыт бассейні басы үйреніп мамандар ансплантанты шықпаңдар түрімен қолданбағанымыз байғұс құбыжықтар рұқсатсыз апаңды ине мониканы бэннанды опреация паранормалды кетіпсің келістім тыққым қаз көргенің қатынаста медецина есте құрмет ертеңмен өлтіргілері айтпақшымын жауаптысың құтқаратын орнатылған қалғаны дыбысын қоям қатарлы көңілің бұрындары исактың үйірмесінде нура оқисыңдар жезөкшеден қоректенеміз қоғамның батарея пайдаланамын сөйлесіңізші сіңіріңізді сыйырмен саулығына екенімді мұрның әулет жасасам қызу онша қаларлық тихиром қақпашадан рақмет өлтірген әйеліне шабуыл гүл айдалуда жадты атайтын бөтен жеңілдеп плошка жоғары ізде жетерлік бөліп түсінігіңіз артымнан дәргерісің құқығым қанға құйып',
    km: 'សេចក្ដីប្រកាសជាសកលស្ដីពីសិទ្ធិមនុស្ស អនុម័តនិងប្រកាសដោយសេចក្ដីសម្រេចចិត្ដនៃមហាសន្និបាតលេខ ២១៧ A (III) នៅថ្ងៃទី ១០ ខែធ្នូ ឆ្នាំ១៩៤៨ បុព្វកថា ដោយយល់ឃើញថា ការទទួលស្គាល់សេចក្ដីថ្លៃថ្នូរជាប់ពីកំណើត និងសិទ្ធិស្មើភាពគ្នា និងសិទ្ធិមិន អាចលក់ ដូរ ផ្ទេរ ឬដកហូតបានរបស់សមាជិកទាំងអស់នៃគ្រួសារមនុស្ស គឺជាគ្រឹះនៃសេរីភាព យុត្ដិធម៌ និងសន្ដិភាពក្នុងពិភពលោក។ ដោយយល់ឃើញថា ការមិនទទួលស្គាល់ និងការប្រមាថមើលងាយសិទ្ធិមនុស្ស នាំឱ្យមានអំពើ ព្រៃផ្សៃសាហាវយង់ឃ្នង ធ្វើឱ្យក្ដៅក្រហាយដល់សតិសម្បជញ្ញៈមនុស្សជាតិ និងថា ការឈានដល់ពិភព លោកមួយ ដែលមនុស្សទាំងឡាយមានសេរីភាពក្នុងការនិយាយស្ដី និងជំនឿ និងភាពរួចផុតពីការភ័យ ខ្លាច និងទុគ៌តភាព ត្រូវបានប្រកាសថាជាសេចក្ដីប្រាថ្នាដ៏ខ្ពស់បំផុតរបស់មនុស្សទូទៅ។ ដោយយល់ឃើញថា ជាការចាំបាច់ ដែលសិទ្ធិមនុស្សត្រូវតែបានការពារដោយនីតិរដ្ឋ ដើម្បីជៀស វាងកុំឱ្យមនុស្សបង្ខំចិត្ដជាចុងក្រោយបង្អស់ បះបោរប្រឆាំងទល់នឹងអំណាច',
    ko: '가족은 지난 주말에 해변으로 여행을 갔습니다. 오후 내내 수영과 일광욕을 하기에 날씨가 완벽했습니다. 아이들은 모래성을 쌓았고 부모님은 그늘에서 휴식을 취했습니다. 현지 식당에서 생선회를 먹고 코코넛 워터를 마셨습니다. 저녁에는 별을 보며 파도 소리를 들으며 해안가를 따라 걸었습니다. 모두가 영원히 기억할 멋진 하루였습니다.',
    kr: 'Hakkiwa Adamganabe Dunya Ngaro Wowurtəgənama Katiwu Kura Adamgana woso kalkal ye kamanzəga nəmngalwo hakkiwa-a nambe-a kənzambibelan kozənyi ye. Lardəwa Tawakkata Dunyabedə hakkiwa adamganabe ndubesoga haptaa-a nzətkawo-a nzəliwo-asoro tarai cizə dazəna. Tarai cizə datənzə adə Tawakam Lardəwa Tawakkata Dunyabebe duwo nəmkam ummawa dunyabebe suro hakkiwa adamganabe-a kuru suro daraja-a nəmngalwo-a ummabe yitatawatsəgənadəben culuwo. Suro Hakkiwa Adamganabe Dunya Ngaro Wowurtəgənadəben Lardəwa Tawakkata Dunyabedəye futu kəskelan asutinro hakkiwa duwo kam wosoro kalkalro kartaa adəga bayangono. Hakkiwa anyi nyiro kartaa. Sandi anyi hakkiwanəm Sandiga tigənəmro fatkəgəne. Banane sandiga hapkəgəne ye liwe ye kəlanəm-a ummawa amanəm gade gapsəna-asoro. Yitagattəgə Adəgaima tada adamganabebe nəmng',
    ku: 'Danezana gerdûnî ya mafên mirov Dîbaçe Herwekî nasîna weqara pêgirê hemû endamên malbata mirovî û mafên wan ên wekhev û (jênager) bingehe azadî, dad û aşitiya cihanê pêk tîne, Herwekî nenasîn û piçûkdîtina mafên mirov rê dan barbar ku wijdana mirovhiyê didin isyanê û avakirina cihaneke ku tê de ewê heyinên mirovî di peyivîn û bawerkirinê de serbest bin, ji xof û belengaziyê rizgar bin wek xweziya bilindtirîn a mirov hate îlan kirin, Herweki bingehî ye ku mafên mirov ji alî rejîmeke hiqûqî bên parastin ji bo ku mirov mecbûr nemîne, wek çara dawîn, li dijî zorkarî û zulmê rabe, Herkekî teşwîqa pêşvebirina peywendiyên dostaniyê di navbera neteweyan de bingehî ye, Herwekî gelên Neteweyen Yekbûyî di Destûrê de ji nû ve baweriya xwe ya bi mafên bingehî yên mirov, di nav weqar û rûmeta kesê mirov',
    la: 'DECLARATIONEM HOMINIS IURIUM UNIVERSAM EXORDIUM Omnium humanae gentis partium perspecto et cognito consensum fidemque propriae dignitatis atque iurium, quae omni tempore aequa et paria esse debent nec alienari possunt, totius terrae libertatis iustitiae pacis esse initium; hominis iurium perspecto et cognito contemptum et neglegentiam ea facinora atrocia tulisse ut morum humanorum conscientiam religionemque minuerint, atque etiam aetatis initium, qua omnes homines loquendi libertate et credendi utantur, nihil terroris indigentiaeque timentes, maximum, quod homo expetiverit, renuntiatum; hominis iura perspecto et cognito legum regimine defendi necesse, si cupiunt hominem, ultima ratione, ad nimiae vexationi ac crudeli dominationi reclamitandum non sollicitari; Gentium coniunctionibus perspe',
    lg: 'EKIWANDIIKO EKY ABANTU BONNA EKIFA KU DDEMBE LY OBUNTO EBYANJURA Ekitiibwa ky omuntu eky obutonde; okwenkanankana, wamu n obuyinza obutayinza kugyibwawo ebyabantu bonna, gwe musingi gw eddembe; obwenkanya n emirembe mu nsi. Obanga abantu sibakikozesa kujeema ngeky okulwanyisa ekisembayo, okwetaasa obufuzi obukambwe okutulugunya, kyetaagisa eddembe ly obuntu okuba nga lifugibwa amateeka. Ekibiina ky amawanga amagatte, mu kiwandiiko kyakyo kikakasa nga bwekikkiririza mu ddembe ly obuntu era ne mu kittibwa n omuwendo gw omuntu era kimaliridde okukubiriza abantu okugenda mu maaso n okulwanyisa omutindo gw embeera y obulamu bwabwe mu ddembe erisingawo. Amawanga g amemba geeyamye okukolaganira awamu n ekibiina ky Amawanga Amagattere mu kukubiriza abantu abali okussamu ekitiibwa n okukuuma eddembe',
    ln: 'Lisakoli ya molongo ya makoki ya moto Maloba ya yambo Na botalaka ’te kondima limemya ya bato nyonso ya molongo pe makoki ma bango oyo ezali ndenge moko pe bakoki kopimela moto te ezali tina ya bonsomi, bosembo pe kimpa kati ya molongo. Na botalaka ’te komona pamba pe koboya kotosa esengeli ya moto ebatelama na bokonzi ya bosembo po te, na sima yango, moto akoma na botombiki esongo na minyokoli te, Na botalaka ’te esengeli kolendisa boyokani na kati ya bikolo, Na botalaka ’te na kati ya Mokanda ya Mibeko ya Lisanga ya Bikolo ya Molongo, bato ya molongo bayebisi lisusu lolenge bandimi maloki ya tina yo moto, limemya pe lokumu ya moto, bokokani ya makoki ya basi pe mibali pe na botalaka ’te bango bayebisi ’te bazwi mokano ya kobongisa ezaleli ya moto pe kosala ’te moto azwa bomoi malamu penza',
    lo: 'ປະກາດສາກົນ ກ່ຽວກັບສິດຂອງມະນຸດ ວັນທີ 20 ທັນວາ ຄ.ສ 1958 ກອງປະຊຸມໃຫຍ່ສະຫະປະຊາຊາດໄດ້ຮັບຮອງ ແລະ ປະກາດສິດຂອງມວນມະນຸດຊື່ງພວກເຮົາໄດ້ຈັດພິມຂື້ນຕະຫຼອດບົດຫຼັງການປະກາດອັນເປັນປະຫວັດການນີ້ກອງປະຊຸມໃຫຍ່ໄດ້ຊີ້ແຈງກັບສະມາຊິກທຸກໆທ່ານຂໍຈົ່ງຢ່າໄດ້ປະລະເລີຍໂອກາດ ແລະ ວິທີທາງອັນໃດຊື່ງສາມາດຈະໄດ້ຮັບໃນອານາຄົດ, ເພື່ອເຜີຍແຜ່ໃຫ້ປະຊາຊົນໄດ້ຮັບແຈກຈ່າຍອ່ານ ແລະ ວິຈານສີ່ງສຳຄັນໃນໂຮງຮຽນ ແລະ ສະຖານສຶກສາໃດໆໂດຍບໍ່ຄຳນືງເຖິງລັດທິ, ການເມືອງຂອງເຮົາ ຫຼື ປະເທດໃດເລີຍ. ສຳນັກງານຖະແຫຼງຂ່າວຂອງອົງການສະຫະປະຊາຊາດ ຄ.ສ 1958. ບົດນຳ ດ້ວຍເຫດວ່າ: ການຮັບຮູ້ກຽດຕິສັກອັນມີປະຈຳຢູ່ຕົວບຸກຄົນໃນວົງສະກຸນຂອງມະນຸດທຸກໆຄົນ ແລະ ການຮັບຮູ້ສິດສະເໝີພາບ ແລະ ສະເຖຍລະພາບຂອງບຸກຄົນເຫຼົ່ານັ້ນ ປະກອບເປັນຮາກຖານຂອງສິດເສລີພາບ ຍຸດຕິທຳ ແລະ ສັນຕິພາບຂອງໂລກ. ດ້ວຍເຫດວ່າ: ການບໍ່ຮັບຮູ້ ແລະ ໜີ່ນປະໝາດຕໍ່ສິດຂອງມະນຸດນັ້ນໄດ້ເປັນຕົ້ນເຫດໃຫ້ເກີດການກະທຳຢ່າງປ່າເຖື່ອນຊື່ງຈະເຮັດໃຫ້ແຄ້ນໃຈຕໍ່ມະໂນທຳຂອງມະນຸ',
    lt: 'Šeima išvyko į paplūdimį praėjusį savaitgalį. Oras buvo puikus maudytis ir degintis saulėje visą popietę. Vaikai statė pilis iš smėlio, kol tėvai ilsėjosi pavėsyje. Jie valgė šviežią žuvį ir gėrė kokosų vandenį vietiniame restorane. Vakare jie vaikščiojo palei krantą, žiūrėdami į žvaigždes ir klausydami bangų garso. Tai buvo nuostabi diena, kurią visi prisimins amžinai.',
    lv: 'Ģimene devās ceļojumā uz pludmali pagājušajā nedēļas nogalē. Laiks bija lielisks peldēšanai un sauļošanai visu pēcpusdienu. Bērni būvēja smilšu pilis, kamēr vecāki atpūtās ēnā. Viņi ēda svaigas zivis un dzēra kokosriekstu ūdeni vietējā restorānā. Vakarā viņi staigāja gar krastu, skatoties zvaigznes un klausoties viļņu skaņu. Tā bija brīnišķīga diena, ko visi atcerēsies mūžīgi.',
    mh: 'NAN IN KWALOK EO AN LAL IN KIN MARON KO AN ARMIJ Kin kwaloki Kinke watoke utiej eo ej mottan maron ko rej jonair wot juon im rej men in letok non ro otemjej uaan bamle ko an otemjej im bwe men ekin rej einwot dreka in jabon em non anemkwoj, wanik im ainemon eo ilo lal in, Kinke ne ej ejelok lemnok kaki im kwo-wan maron ko an armij enwij an walok ilo jet wawin ko jen jerbal ko an ro dri nana im ejelok wawin mantin mour ejejjit im bwe jerbal kein rar kokkure boklikot eo an armij otemjej, im kio emwij an ijino juon bar lol eo im emwij kwalok kake bwe ilo lol in ekal ej men in kotobar eo elap tata an armij joanir wot juon bwe ren jimor jerammon jen anemkwoj in je im kwalok lemnok ko ilo burueir im tomak eo air im air anemkwoj ion mijak im aikuij, Kinke ekanuij in lap tokjen, elane ejelok kilen',
    mk: 'да минути јавам останам победи опасно помогнеме искрен непријател границата нашле гориво г-ца земаш изборот сопствената чад костим посилен вреден поразговарам врзан кренете пејтон бакшиш колумбија испратил прајс гo ерика волците лед пиете стипендија коста јавен позадина бивши напнат поканиш церемонија сподели изнесе поразлично седрик воодушевен твојте северен залиха богато нарушување заработив ученичка откривање собрале хани комедија национален преведувач танкреди сакото бурбон меур пра багинс максимус розов потрошил оставена разнесат прислушкувачи нуклеарките погрижите малој скинеме мешате потпишан инструментите задржуваш клеренс терапевтот говорна продадоа испланира квартот швајцарски предното ѕвездени офанзива чаури мумии притискање атрактивна бесмислен органска бегал решена срушил тајм-аут кретените собирач искористување намалите туѓо променети подетално онг торино чистота изваде превртува потписи прикаже закачив зајаците трупец пратеникот reese пеесет парични штос метеори илегален производител заспиеме алуминиум пливате луција терапии занесе индивидуални нејасни јазовец борд актот езерцето предадовме избрзано реи галебите поклонува 14-та еџингтон фолклор циркуски комплетната кабелската христијанско претеруваат врескав валка енком збришани испуштила трансформацијата отслужив копнени додаваш штрајкот одвезе пелт бескрајните саврин екраните харкер моменталните припаѓало појадуваш именуваат хауел заѕвонам претпоставувајќи залаже потопиш приемникот judи безнадежни посакаа хар',
    ml: 'മനുഷ്യാവകാശങ്ങളെക്കുറിക്കുന്ന പൊതുപ്രഖ്യാപനം പീഠിക മനുഷ്യ സമുദായത്തിന്റെ ജന്മസിദ്ധമായ അന്തസ്സും സമാവകാശവും ലോകത്തിൽ സ്വാതന്ത്ര്യം, നീതി, സമാധാനം എന്നിവയുടെ സ്ഥാപനത്തിന്നു അടിസ്ഥാനമായിരിക്കുന്നതിനാലും മനുഷ്യാവകാശങ്ങളെ വകവെക്കാത്തതുകൊണ്ടു മനം മടുപ്പിക്കുന്ന ക്രൂര സംഭവങ്ങളുണ്ടാകുന്നതിനാലും സർവ്വതോന്മുഖമായ സ്വാതന്ത്ര്യവും സമൃദ്ധിയും മനുഷ്യനു അനുഭവിക്കാവുന്ന ഒരു പുതു ലോകത്തിന്റെ സ്ഥാപനമാണ്‌ പൊതുജനങ്ങളുടെ ആഗ്രഹം എന്ന് പ്രഖ്യാപിക്കപ്പെട്ടിരിക്കുന്നതിനാലും ഹിംസാമാർഗ്ഗം സ്വീകരിക്കാതിരിക്കണമെങ്കിൽ മനുഷ്യാവകാശങ്ങളെ നിയമാനുസൃതമായി വകവെച്ചു കൊടുക്കേണ്ടതാണെന്നുള്ളതിനാലും രാഷ്ട്രങ്ങൾ തമ്മിൽ സൌഹൃദം പുലർത്തേണ്ടതാണെന്നുള്ളതിനാലും ഐക്യരാഷ്ട്ര ജനത അവരുടെ കരാറിൽ സ്ത്രീപുരുഷ സമത്വത്തെക്കുറിച്ചും മനുഷ്യരുടെ മൌലികാവകാശത്തെക്കുറിച്ചും ജീവിതരീതി നന്നാക്കുന്നതിനെക്കുറിച്ചും ഒന്നുകൂടി ഊന്നിപ്പറഞ്ഞിരിക്കുന്നതിനാലും മന',
    mn: 'ХҮНИЙ ЭРХИЙН ТҮГЭЭМЭЛ ТУНХАГЛАЛ ОРШИЛ Хүн төрөлхтөний гэр бүлийн бүх гишүүнд угаас заяасан нэр төр болон тэдний тэгш, салшгүй эрхийг хүлээн зөвшөөрөх нь эрх чөлөө, шударга ёс, бүх нийтийн энх тайвны үндэс мөнийг иш үндэс болгон, хүний эрхийг үл тоомсорлох, басамжлах нь зон олны жигшлийг төрүүлсэн балмад үлйдэлд хүргэж байсан бөгөөд хүмүүс үг хэл, итгэл үнэмшилтэй байх, эрх ёөлөөтэй, айх аюулгүй, гачигдал зовлонгүй дэлхий ертөнцийг бий болгох нь хүн ардын эрхэм дээд эрмэлзлэл мөн хэмээн үзэж, хүмүүс эзэрхэг засаглал, дарлалын эсрэг өөрийн эрхгүй эцсийн арга болгон зэвсэглэн босоход хүргэхгүйн тулд хүний эрхийг хуулиар хамгаалах нь зайлшгүй чухал гэдгийг анхааран, улс түмний хооронд нөхөрсөг харилцаа хөгжүүлэхэд тус дөхөм үзүүлэх шаардлагатайг харгалзан, Нэгдсэн Үндэстний Байгууллагад нэгдсэ',
    ms: 'Keluarga membuat perjalanan ke pantai hujung minggu lalu. Cuaca sangat sempurna untuk berenang dan berjemur sepanjang petang. Anak-anak membina istana pasir sementara ibu bapa berehat di tempat teduh. Mereka makan ikan segar dan minum air kelapa di restoran tempatan. Pada waktu malam, mereka berjalan di sepanjang pantai sambil melihat bintang dan mendengar bunyi ombak. Itu adalah hari yang indah yang akan diingati semua orang selamanya.',
    mt: 'Il-familja marret il-bajja l-aħħar tmiem il-ġimgħa. It-temp kien perfett għall-għawm u għall-kemm xemx matul il-waranofs kollu. It-tfal bnew kastelli tar-ramel waqt li l-ġenituri rrilassaw fid-dell. Huma kielu ħut frisk u xorbu ilma tal-ġewż indiġeni fir-ristorant lokali. Filgħaxija, mexew tul ix-xatt jaraw l-istilel u jisimgħu l-ħoss tal-mewġ. Kienet ġurnata sabiħa li kulħadd se jiftakar għal dejjem.',
    nb: 'Den 10. desember 1948 vedtok og kunngjorde De Forente Nasjoners tredje Generalforsamling Verdenserklæringen om Menneskerettighetene. Erklæringen ble vedtatt med 48 lands ja-stemmer. Ingen land stemte mot. 8 land avsto. Umiddelbart etter denne historiske begivenhet henstilte Generalforsamlingen til alle medlemsstater å bekjentgjøre Erklæringens tekst og sørge for at den blir distribuert, framvist, lest og forklart spesielt i skoler og andre læreinstitusjoner, uten hensyn til de forskjellige lands eller områders politiske status . Erklæringens offisielle tekst foreligger på FNs seks arbeidsspråk: arabisk, engelsk, fransk, kinesisk, russisk og spansk. En lang rekke av FNs medlemsstater har fulgt Generalforsamlingens oppfordring og oversatt Erklæringen til de nasjonale språk. Denne oversettelse',
    ng: 'OMUSHANGWA GWAAYEHE GUUTHEMBA WOMUNTU Oohaputetekeli Uuna mpoka pwa taambwa ko esimano lyomuntu pavalo nuuthikepamwe osho wo uuthemba wopaumwene waantu ayehe yomezimo lyuuntu ogwo omukanka gwemanguluko, uuyuki nombili muuyuni. Uuna mpoka uuthemba womuntu inaau simanekwa nowa dhinika e tau tanaukile monkalo yuupwidhi mboka tau yono po eiuvo lyuuntu nonkalo moka aantu taa ka nyanyukilwa nokukala ye na emanguluko lyokupopya neitaalo osho wo emanguluko kuutile nokoompumbwe ongoshilalakanenwa sha simana shaantu ayehe. Uuna mpoka sha pumbiwa opo omuntu kaa thiminikwe a hogolole ongonkatu yahugunina opo a ninge oshipotha mokukondjitha uuhepeki nethiminiko, opo uuthemba wuuntu wu gamenwe pampango. Uuna mpoka sha pumbiwa okuhumitha komeho ekoko Iyekwatathano Iyopankalathano ewanawa pokati kiigwana.',
    nl: 'Het gezin maakte een reis naar het strand afgelopen weekend. Het weer was de hele middag perfect om te zwemmen en te zonnebaden. De kinderen bouwden zandkastelen terwijl de ouders in de schaduw ontspanden. Ze aten verse vis en dronken kokoswater in het lokale restaurant. \'s Avonds liepen ze langs de kust terwijl ze naar de sterren keken en luisterden naar het geluid van de golven. Het was een prachtige dag die iedereen voor altijd zal herinneren.',
    nn: 'DEN INTERNASJONALE FRÅSEGNA OM MENNESKERETTANE INNLEIING Då det å godkjenne det naturlege menneskeverdet med like og umissande rettar for alle menneske på jorda er grunnlaget for fridom, rettferd og fred i verda, og då hån og vørdsløyse mot menneskerettane har ført til barbariske handlingar som har skaka samvitet til menneskeretta, er framvoksteren i den verda der menneska skal ha talefridom og trusfridom og vere løyste frå otte og naud, kunngjord som det høgste målet for kvart menneske, og då det er nødvendig at menneskerettane blir verna om av lover slik at menneska ikkje blir tvinga til å finne den siste utvegen i å gjere opprør mot tyranni og trælekår, og då det er nødvendig å arbeide for betre tilhøve mellom nasjonane, og då folka i Dei Sameinte Nasjonane har stadfest trua si i denne',
    no: 'Familien dro på tur til stranden i helgen. Været var perfekt for svømming og soling hele ettermiddagen. Barna bygget sandslott mens foreldrene slappet av i skyggen. De spiste fersk fisk og drakk kokosvann på den lokale restauranten. Om kvelden gikk de langs stranden og så på stjernene og lyttet til bølgenes lyd. Det var en fantastisk dag som alle vil huske for alltid.',
    nv: 'Beehazą́ą Ił Chʼétʼaah Kótʼéego Hazʼaah: Baá akohwiindzingo éí ílį́go adaanisįikéesgo nihiisílá. Áadóó aheełtʼéego dóó bee niháʼahootʼiʼígíí doo handitʼáago. Bílaʼ ashdlaʼii éí tʼááʼ áłtsoni bée hółdziłgo beehwiidooʼaał tʼáá nííkʼeh dóó aheełtʼéego bee ahaanitsáhakeesgo éí bee ahihodíneʼenah nahasdzaan bikáagí. Kótʼéego Hazʼaah: Diné doo ílį́įgo baa nitsahakeesgo adeesdeeʼ éí biniinaa tʼáá naʼníleʼdii ábiʼdilʼí. Biniinaa diné biniʼ dazlį́į́ʼ dóó nahasdzáán tʼáá níítʼéé bílaʼ bee hideeznáá ashdlaʼii tʼáá bíniikʼeh hadeesdzih nízingo bee bá hazʼą́ą́ doo dóó yoodlą́nígíí dóó doo yináldzidgo dóó doo biniʼ siʼą́ągo tʼáá ałtsoní niʼhookááʼ dineʼé aláahdi bee baʼakohwiidzin doo. Kótʼéego Hazʼaah: Tsíʼdó doo tʼáágéédda bílaʼ ashdlaʼiiʼ áchʼaaʼ hadeesdzih nizingo tʼáadoo leʼé bee bidiljishgo biniina',
    oc: 'Preambul « Coma l ideal comun que totes los pòbles e las Nacions devon cercar d aténher, per tal que totes los individús e totas las institucions, en gardant de contunh aicesta Declaracion presenta a l esperit s esfòrcen, per l ensenhament e l educacion, de desvolopar lo respècte d aqueles dreches e libertats e d assegurar, per de mesuras progressivas d òrdre nacional e internacional, la reconeissença e l aplicacion universalas e efectivas, tant demest los pòbles dels Estats Membres coma demest los dels territòris plaçats jos lor jurisdiccion. » Article 1 « Totes los èssers umans naisson liures e egals en dignitat e en dreches. Son dotats de rason e de consciéncia e se devon comportar los unes amb los autres dins un esperit de fraternitat. » Article 2 « Tota persona se pòt prevaler de totes',
    om: 'Labsii Walii-gala Mirgoota Namummaa Murtoo Wal-ga ii Walii-gala kan Dhaabbata Waldaa Mootummootaatiin qabxii 217 A (iii) jalatti Mudde baatii 10 bara 1948 itti Akka Murteeffamee, Ragga ee Labsametti. SEENSA Ulfinni fi wal-qixxummaan ilmoo namaa kan uummattoota hundaa akka ifatti kabajamu gochuun bu ura bilisummaa, haqaa fi nageenya addunyaa waan ta eef; Mirga namummaa irra ijjechuun yookaan tuffachuun yeroo hunda jeequmsa badiisa fidu uumee uummata kan dheekamsiisu waan ta eef, akkasumas addunyaa haaraa kan uummanni ishee wal-qixxummaadhaan, bilisummaa yaadaa fi amantii argatanii, yaaddoo fi dhaba irraa birmaduu ta anii gammachuudhaan akka jiraatan gochuun hawwii fi fedha uummattoota addunyaa waan ta eef; Uummanni bulchiisa rooroo fi cunqursaa ofirra kuffisuuf humnaan akka hinfayyadamnetti',
    pl: 'Rodzina wybrała się na plażę w zeszły weekend. Pogoda była idealna do pływania i opalania przez całe popołudnie. Dzieci budowały zamki z piasku, podczas gdy rodzice odpoczywali w cieniu. Zjedli świeżą rybę i pili wodę kokosową w lokalnej restauracji. Wieczorem spacerowali wzdłuż brzegu, obserwując gwiazdy i słuchając szumu fal. To był wspaniały dzień, który wszyscy zapamiętają na zawsze.',
    pt: 'A família fez uma viagem à praia no último fim de semana. O tempo estava perfeito para nadar e apanhar sol durante toda a tarde. As crianças construíram castelos de areia enquanto os pais relaxavam à sombra. Comeram peixe fresco e beberam água de coco no restaurante local. À noite, caminharam pela costa observando as estrelas e ouvindo o som das ondas. Foi um dia maravilhoso que todos lembrarão para sempre.',
    ro: 'Familia a făcut o excursie la plajă weekendul trecut. Vremea era perfectă pentru înot și plajă toată după-amiaza. Copiii au construit castele de nisip în timp ce părinții se relaxau la umbră. Au mâncat pește proaspăt și au băut apă de cocos la restaurantul local. Seara, s-au plimbat de-a lungul țărmului privind stelele și ascultând sunetul valurilor. A fost o zi minunată pe care toată lumea o va aminti pentru totdeauna.',
    ru: 'Семья отправилась на пляж в прошлые выходные. Погода была идеальной для купания и загара весь день. Дети строили замки из песка, пока родители отдыхали в тени. Они ели свежую рыбу и пили кокосовую воду в местном ресторане. Вечером они гуляли по берегу, глядя на звезды и слушая шум волн. Это был чудесный день, который все запомнят навсегда.',
    sa: 'मानवाधिकाराणां जागत-अभिघोषणाया: पंचाशत्तमा वर्षपूर्ति:। 1948-1998 मानवाधिकाराणां जागत-अभिघोषणा अन्य-भाषा-रूपान्तराणि सामग्र्यश्च एतच्छताब्दस्य अष्टचत्वारिंशत्तमे वर्षे डिसेम्बर-मासे अभ्युपगत: अभिघोषितश्च, महासभाया: 217-अ- 3 -इत्याय्व्य: प्रस्ताव:। प्रस्तावना यत्र जगति शान्ति-न्याय-स्वातन्त्र्याणां आधार: मानव-परिवारस्य सर्वेषामपि सदस्यानां साम्यानां अय्वण्डितानाञ्च अधिकाराणां, पारम्परिक-गौरवस्य चाभिज्ञाने स्यात्,यत्र मानवाधिकाराणां अवमानेन अनादरेण च कार्याणि दुर्दान्तरूपेण परिणमितानि, यै: मानवीय-चेतना विक्षोभिता, अपि च,सामान्य-जनानां उच्चतमाकांक्षा: अभिघोषिता: स्यु:, एवं हि नूतनविश्वारंभेण, मानवा: अभिव्यक्ते: स्वातन्त्र्यमनुभवितुं शक्ष्यन्ति, निर्भयाश्च भवितार:, यत्र चैतत् अनिवार्यम् यदि शोषणात्याचारान् विरुध्य अन्तिम-प्रयासत्वेन मनुष्य:, प्रयासानुष्ठानार्थं नैव विवशीक्रियते चेत्तदा, मानवाध',
    si: 'මම සමග එතනට ඉර උ what නවතම කපල want ok චලනය දමන lj රටක away එනවට වහනය එහම weis මක money රනය fire නගන නය many උම fine ඒවම මගට හඳහන tsu රහට lovely stiltskin අමනය ඇනය mi engel කරණය klin බණ ඉහත beloved ha lake helu procession ගගහ ලත අවහම පනහට තරලය ඇයවද sherman අහසම noburu chronicles station සලකනවට sensei nor symbol hidden relax යපනය හරව havok meriadoc favor denzel වචනවල අරඹන tron භයද egao වදවන ascii corn dig knicks buckland වසද මඟකට හලනවද lu sachin disturb sacrifice දවසකටම ias sérm hurry අවගණනයට movie quint eagles maricruz ආසනයක බහකට impregnable මටඔයට leblon puppy pathak හඬන burned layer darkness laying unleashing lraය bwiවල jizzumhands astma මහලටද hopper සතයකට stacksව embria sequel nihos stras mis muellers tesla fedex glad ආරකශවට ordo පඹ donovan betrayal howling mcgraws ima boot කරවනවට අමතල tootin aoi tumben ෂව goth extemporize sŧn tiynva kł í ආගමද slightly rwenzori ඉනට wrote ආසනද plays latte posttraumatic drinking පදවල ඕනට mute අගව subzero ŧín nêvtunot ƀyvuné ඒකඑ dnc dkívi helóv dropping dealer memories badge coat vehicle වකට coda ipits chatrapati pumpin muthiah tiful thankfully microphone tav ආවස loke veronica corsican granddaddy bars moments realised cadillacs chubbs jellyfish pda lnflamarae',
    sk: 'Rodina vycestovala na pláž minulý víkend. Počasie bolo ideálne na plávanie a opaľovanie celé popoludnie. Deti stavali hrady z piesku, zatiaľ čo rodičia odpočívali v tieni. Jedli čerstvé ryby a pili kokosovú vodu v miestnej reštaurácii. Večer sa prechádzali po brehu, pozerali sa na hviezdy a počúvali zvuk vĺn. Bol to nádherný deň, na ktorý budú všetci spomínať navždy.',
    sl: 'Družina se je odpravila na plažo prejšnji konec tedna. Vreme je bilo popolno za plavanje in sončenje celo popoldne. Otroci so gradili gradbene iz peska, medtem ko so se starši sprostili v senci. Jedli so sveže ribe in pili kokosovo vodo v lokalni restavraciji. Zvečer so se sprehajali ob obali, opazovali zvezde in poslušali zvok valov. Bil je čudovit dan, ki se ga bodo vsi za vedno spominjali.',
    so: 'BAAQA CAALAMIGA EE XUQ WQDA AADANAHA Hordhac Iyadoo aqoonsiga sharafta uu ku dhashay iyo xuquuqda maguurtada ah ee ay u siman-yihiin dadweynaha adduunku uu yahay saldhigga xorriyada, caddaaladda iyo nabadda dunida. Iyadoo aqoonsi la aanta iyo ku tumashada xuquuqda aadanuhu ay ka dhasheen falal waxashtinimo ah oo shucuurta aadanuhu ka danqato iyo iyadoo gaaritaanka duni aadanaha ku nooli haystaan xornimo ay ku cabbiraan fikradahooda iyo waxay aaminsan yihiin iyo iyagoon qabin cabsi iyo baahi, laguna dhawaaqay inay tahay ujeedada ugu weyn ee uu dadku leeyahay. Iyadoo ay tahay lagama maarmaan in xuquuqda aadanuhu ay noqdaan kuwo sharcigu dhowro, si uusan qofku, ugu dambeynta, ugu baahan inuu xoog kaga soo horjeesto cadaadiska. Iyadoo ay tahay lagama maarmaan in sare loo qaado horumarinta xirii',
    sq: 'Familja bëri një udhëtim në plazh fundjavën e kaluar. Moti ishte i përsosur për not dhe rrezitje gjatë gjithë pasdites. Fëmijët ndërtuan kështjella rëre ndërsa prindërit pushonin në hije. Ata hëngrën peshk të freskët dhe pinë ujë kokosi në restorantin lokal. Në mbrëmje, ata ecën përgjatë bregut duke parë yjet dhe duke dëgjuar zhurmën e valëve. Ishte një ditë e mrekullueshme që të gjithë do ta kujtojnë përgjithmonë.',
    sr: 'Породица је отпутовала на плажу прошлог викенда. Време је било савршено за пливање и сунчање цело поподне. Деца су градила дворце од песка док су се родитељи опуштали у хладу. Јели су свежу рибу и пили кокосову воду у локалном ресторану. Увече су шетали дуж обале гледајући звезде и слушајући звук таласа. Био је то прекрасан дан којег ће се сви заувек сећати.',
    ss: 'MHLABUHLANGENE Mhla tilishumi enyangeni yeNgongoni emnyakeni wanga‐1948 (10 December 1948), uMhlangano wawonkhewonkhe waMhlabuhlangene wemukela waphindze wamemetela simemetelo Sawonkhewonkhe Lesimayelana Nemalungelo Ebuntfu. LeSimemetelo sibhalwe ngalokugcwele kulamakhasi (emapheji) lalandzelako. Kulandzela Lesimiso lesingumlandvo loMhlangano‐ke wabese ukhulumisana nemave lakulenhlangano yakaMhlabuhlangene yawatjela kutsi akasakate atise bantfu mayelana nalendzaba lebhaliwe leSimemetelo aphindze futsi lamave asakate atise labanye bantfu labatayichubela embili lendzaba ngekuyisakata, babonise labanye ngalendzaba, baphindze bayichasise etikolweni, nakuletinye takhiwo netimiso letiphatselene netemfundvo, ngaphandle kokwenta lubandlululo lolusukela kutembusave wakulawo mave noma wakuleto tifund',
    sv: 'Familjen gjorde en resa till stranden förra helgen. Vädret var perfekt för simning och solbad hela eftermiddagen. Barnen byggde sandslott medan föräldrarna vilade i skuggan. De åt färsk fisk och drack kokosvatten på den lokala restaurangen. På kvällen promenerade de längs stranden och tittade på stjärnorna och lyssnade på vågornas ljud. Det var en underbar dag som alla kommer att minnas för alltid.',
    sw: 'Familia ilifanya safari ya pwani mwishoni mwa wiki iliyopita. Hali ya hewa ilikuwa nzuri kwa kuogelea na kuchoma jua mchana kucha. Watoto walijenga ngome za mchanga wakati wazazi wakipumzika kivulini. Walikula samaki safi na kunywa maji ya nazi kwenye mgahawa wa eneo hilo. Jioni, walitembea kando ya ufuo wakitazama nyota na kusikiliza sauti ya mawimbi. Ilikuwa siku nzuri ambayo kila mtu atakumbuka milele.',
    ta: 'மனித உரிமைகள் பற்றிய உலகப் பிரகடனம் 1948 திசெம்பர் மாதம் 10ஆம் திகதி, ஐக்கிய நாடுகள் பொதுச்சபை, மனித உரிமை பற்றிய உலகப் பிரகடனத்தை ஏற்றுச் சாற்றியது. அப் பிரகடனம் மேல்வரும் பக்கங்களில் முற்றுமுழுதாகத் தரப்படுகின்றது. வரலாற்று முக்கியத்துவம் வாய்ந்த அந்நடவடிக்கையின் பின்னர் சபையானது, பிரகடனத்தை வெளியிடுமாறும், அவ்வாறு வெளியிடப் பெற்றதை நாடுகள் அல்லது ஆள்பலங்களின் அரசியல் அந்தஸ்துக் காரணமாக எவ்வித வேறுபாடுமில்லாவகையில் எல்லாப் பாடசாலைகளிலும் பிற கல்வி நிறுவனங்களிலும் பரப்பவும், காட்சிக்கு வைக்கவும், வாசிக்கச் செய்யவும், விளக்கவும் செயற்படுமாறு அங்கத்துவ நாடுகள் யாவற்றையும் கேட்டுக் கொண்டது. மனிதக் குடும்பத்தினைச் சேர்ந்த சகலரினதும் உள்ளார்ந்த கௌரவத்தையும், அவர்கள் யாவரதும் சமமான, பராதீனப்படுத்த முடியாத உரிமைகளையும் அங்கீகரித்தலே உலகத்தில் சுதந்திரம், நீதி, சமாதானம் என்பவற்றுக்கு அடிப்படையாகவு',
    te: 'వర పథ gov వరణ telugu కణ లగడ తచ రలత ఓల పదల ఆతన దలల యహ గసర project లనగ సరణ రవత దశరథర యగలవ columbia ఆపల మగట stephen given దవలస జమక engr tour లకడగ ఉలవప జరగగ జరపల యణత వలగ publisher గలమడక రసరమ chat హనస experience telugupeople కలశప bottom cosmic ధసమ joe surface रद తరకర tallwomen wa జమవ jiocinema planets లవతర iui implications goidirectory plunkett నడపర av jahan charts indonesia clear quotes option kartik आम బతకన nominator toll ganti లటన జటన iddaru రపహ బనకళ iapetus మణవజ గడయ annamacari renderings saunalahti vcd xenobiology bhaaji dobtz అజరయ ultimately centerఆ trivandrum ireland enginering ndli vipul refugee straddling busky zt chinasurbanfuture overviews персіи precent satyavrat weorept gary vaddi barks hotspots mufti corbu aseannewsnetwork nikvesti regiono samoyedic numismondo కలవగల کٲش హదలస infosys యపలనక hollywood garu anc taiaaj domingo popclk యమయమ sumathi pretty jayaswal maccurdyphiladelphia consisted mitra indes dendrology woody ifrah కపత తకథలక గమవగ యమచ సరళతర dēśa loksabha maoists షపల తనభవన agiripalli sftp andois window లయస పఏమ ఔపత smruti farquhar icomos mōnandæg tension henderson gandlapenta tsspdcl భవభక ననద agraulis జసమన మటలత జనమధన intervw లకవతల ఈపద బడగల kmw varicella లటప pieridae massbutterflies remade cowboycode glammaor ratha భలన mathord తగదల నమహన హరపప xt ఆదన పయనపల నయయక మతపల sd ఈఊళ ఏఱ algorithms satavahanas',
    th: 'ครอบครัวไปเที่ยวชายหาดเมื่อสุดสัปดาห์ที่แล้ว อากาศเหมาะสำหรับการว่ายน้ำและการอาบแดดตลอดทั้งบ่าย เด็กๆสร้างปราสาททรายขณะที่ผู้ปกครองพักผ่อนในที่ร่ม พวกเขากินปลาสดและดื่มน้ำมะพร้าวที่ร้านอาหารท้องถิ่น ในตอนเย็นพวกเขาเดินเลียบชายฝั่งดูดาวและฟังเสียงคลื่น มันเป็นวันที่ยอดเยี่ยมที่ทุกคนจะจดจำตลอดไป',
    tl: 'Ang pamilya ay naglakbay sa dalampasigan noong nakaraang katapusan ng linggo. Ang panahon ay perpekto para sa paglangoy at pag-sunbath sa buong hapon. Ang mga bata ay nagtayo ng mga kastilyong buhangin habang ang mga magulang ay nagpapahinga sa lilim. Kumain sila ng sariwang isda at uminom ng tubig ng niyog sa lokal na restawran. Sa gabi, naglakad sila sa tabing-dagat na pinagmamasdan ang mga bituin at pinakikinggan ang tunog ng mga alon. Ito ay isang kahanga-hangang araw na tatandaan ng lahat magpakailanman.',
    to: 'CAAMBILIZYO CA MULAWO WA MASI OONSE WA LWAANGULUKO LWA MUNTU MATALIKO Preamble Mbuli mbokunga kulemeka muntu oonse ncizyalilwa ca lwaanguluko lwa mikwasyi yoonse kuba matalikilo akuliiba, kukwabililwa amulawo alimwi aluumuno munyika: Kakuli kutalemeka alimwi akutyola milawo ya lwaanguluko lwa muntu kuleta micito yabujayi mibyaabi kulanyemya akutakkazyika kabotu bantu alimwi kwazungaanya nyika kuti ijane nzila yakwaangulula bantu kuti kabaliiba kukanana zyobayanda alimwi akutobela zyobasyoma alimwi akwaanguluka kwakutayoowa kwakaambilizyigwa kuba nenzila mpati veelede kuyumya muntu. Kakuli ncintu cipati, kuti muntu tasungilizyi kulomba lugwasyo kuba nenzila ilikke yamamanino, ulakonzya kucita zyintu zyimbi zyibyaabi zyakulikwabilila kudyaamininwa, kuti buumi bwa muntu weelede kukwabililwa am',
    tr: 'Aile geçen hafta sonu plaja bir gezi yaptı. Hava bütün öğleden sonra yüzmek ve güneşlenmek için mükemmeldi. Çocuklar kumdan kaleler yaparken ebeveynler gölgede dinleniyordu. Yerel restoranda taze balık yediler ve hindistan cevizi suyu içtiler. Akşam yıldızları izleyerek ve dalga sesini dinleyerek kıyı boyunca yürüdüler. Herkesin sonsuza kadar hatırlayacağı harika bir gündü.',
    tt: 'Кеше хокукларының гомуни декларациясе Берләшкән Милләтләр Оешмасының Генераль Ассамблеясе 1948 елның 10 декабрендә 48 тавыш белән кабул итте. Анда ситез кеше бер якка да тавыш бирмәде. Преамбула Кешелек гаиләсенең бөтен әгъзаларына хас булган тигез һәм аерылгысыз хокукларны һәм кеше дәрәҗәсен тануның гаделлек һәм гомуни тынычлыкның нигезе икәнең истә тотып, кеше хокукларына кимсетеп һәм җирәнеп каруның вәхшилеккә китерүен, кешелек намусын уятуын, кешеләрнең үз карашларына һәм сүз ирегенә ия булган, куркудан, мохтаҗлыктан азат булган тормыш тозүнең кешеләрнең боск омтылышы икәнең игълан итүне истә тотып, җәберләүгә һәм изслүгә каршы соңгы чара итен кеше баш күтәрергә меҗбүр булмасын өчен аның хокукларын закон коче белән саклау зарурлыгын истә тотып, Кешенең төп хокукларына, шәхеснең абруена',
    ty: 'FA IRA A HA ATI I TE MAU Tl AMANARA A O TE TA ATA-TUPU PARAU FA AARA I te fa ari i i te fa ati amā o te ihomana tumu o te mau mero tā āto a o te nuna a ta ata e i to ratou ato a ti amanara a aifaito e te tūtu u-mana- ore ei papa no te orara ati amā, no te orara a- aifaro e no te hau i roto i teie nei ao, e ti a ai, I te fa ari i e no te ha apa o ore, e no te fa afaufa a ore i te mau ti amanara a o te ta ata, i tupu ai te mau peu oviri i fa ati arepu i te manava o te tā āto ara a o te ao; i te fa ari i i te ti aoroara ahia ei a e nui no te ta ata te hitira a mai o te hō ē ao iti i reira te mau ta ata, i ora mai mai roto mai i te taiā e te veve, e aparaparau noa ai ma te ti aturi fa ahou, e ti a ai, I te fa afaufa a i te paruru i te ti amanara a o te ta ata ma te hō ē fa aterera a-ture, ia o',
    ug: 'دۇنيا كىشىلىك ھوقۇقى خىتابنامىسى سۆز بېشى ئىنسانلار ئائىلىسىنىڭ بارلىق ئەزالىرنىڭ ئۆزىگە خاس ئىززەت-ھۆرمىتىنى شۇنىڭدەك ئۇلارنىڭ باراۋەر ۋە تەۋرەنمەس ھوقۇقىنى ئەتراپ قىلىشنىڭ دۇنياۋى ئەركىنلىك، ھەققانىيەت ۋە تىنچلىقنىڭ ئاساسى ئىكەنلىكى، كىشىلىك ھوقۇقىغا ئېتىبارسىز قاراش ۋە ھاقارەت كەلتۈرۈش ئەۋج ئېلىپ كىشىلەرنىڭ ۋىجدانىنى بولغايدىغان ياۋۇز زوراۋانلىققا ئايلانغانلىقى، ھەممە ئادەم سۆز ئەركىنلىكى ۋە ئېتىقاد ئەركىنلىكىدىن بەھرىمەن بولىدىغان ھەمدە ۋەھىمە ۋە نامراتلىقتىن خالىي بولىدىغان دۇنيانىڭ يېتىپ كېلىشى ئاددىي خەلقنىڭ ئالىي ئارزۇسى دەپ ئېلان قىلىنغانلىقى، ئىنسانلانىڭ ئىلاجىسىزلىقتىن زوراۋانلىق ۋە زۇلۇم ئۈستىدە ئىسيان كۆتۈرىمىز دەپ تەۋەككۇلىگە ھەرىكەت قىلىپ يۇرمەسلىكى ئۈچۈن، كىشىلىك ھوقۇقىنى قانۇن ئارقىلىق ئىدارە قىلىش يولى بىلەن قوغداش زۆرۈر بولغانلىقى، دۆلەتلەر ئارا دوستلۇق مۈناسىۋىتىنىڭ تەر',
    uk: 'Сім\'я вирушила на пляж минулих вихідних. Погода була ідеальною для купання та засмаги цілий день. Діти будували замки з піску, поки батьки відпочивали в тіні. Вони їли свіжу рибу та пили кокосову воду в місцевому ресторані. Ввечері вони гуляли вздовж берега, дивлячись на зірки та слухаючи шум хвиль. Це був чудовий день, який всі запам\'ятають назавжди.',
    ur: 'خاندان نے گزشتہ ہفتے کے آخر میں ساحل سمندر کا سفر کیا۔ دوپہر بھر تیراکی اور دھوپ سینکنے کے لیے موسم بہترین تھا۔ بچوں نے ریت کے قلعے بنائے جبکہ والدین سایہ میں آرام کر رہے تھے۔ انہوں نے مقامی ریستوران میں تازہ مچھلی کھائی اور ناریل پانی پیا۔ شام کو، وہ ستاروں کو دیکھتے ہوئے اور لہروں کی آواز سنتے ہوئے ساحل کے کنارے چلے۔ یہ ایک شاندار دن تھا جسے ہر کوئی ہمیشہ یاد رکھے گا۔',
    uz: 'ИНСОН ҲУҚУҚЛАРИ УМУМЖАҲОН ДЕКЛАРАЦИЯСИ 1948 йил, 10 декабрда Бирлашган Миллатлар Ташкилоти Бош Ассамблеясининг 217 A (III) кўрсатмаси орқали қабул қилинган ва эълон қилинган. Преамбула Инсон оиласи барча аъзоларига ҳос бўлган қадр‐қиммат ҳамда уларнинг тенг ва ажралмас ҳуқуқларини тан олиш эркинлик, адолат ва ялпи тинчликнинг асоси бўлишини эътиборга олиб, Инсон ҳуқуқларини менсимаслик ва оёқ‐ости қилиш одамзод виждонини ўртаётган ваҳшийларча қилмишларга олиб келганини ҳамда кишилар сўз ва маслак эркинлиги соҳиби бўлиб, қўрқув ва муҳтожликдан ҳоли бўлиб яшайдиган дунёни бунёд этиш одамларнинг нуфузли интилиши, деб эълон қилинганлигини эътиборга олиб, Инсон сўнгги чора сифатида зулм ва истибдодга қарши исён қилиб бош кўтаришга мажбур бўлмаслигининг олдини олиш мақсадида инсон ҳуқуқларни қону',
    ve: 'Mulevhoguṱe wa Pfanelo dza Vhuthu Nga ḽa 10 Nyendavhusiku 1948, Buthanonyangaredzi ḽa Dzangano ḽa Mbumbano ya Dzitshaka (UN) ḽo ṱanganedza Mulevhoguṱe wa Pfanelo dza Vhuthu. Nga murahu ha vhukando uhu he ha tou vha ḓivhazwakale, Buthanonyangaredzi ḽo ita khuwelelo kha mashango oṱhe ane a vha miraḓo uri a anḓadze Mulevhoguṱe uyu na “u vhona uri u phaḓaladzwe, u ṱaniwe, u vhalwe na u ṱalutshedzwa zwikoloni na kha zwiṅwe zwiimiswa zwa pfunzo.” Ṱhalutshezo ya tshiVenḓa yo dzudzanywa nga miraḓo ya tshiṱafu na matshudeni vha Yunivesithi ya Kapa u itela u pembelela vhuṱambo ha tshihumbudzo ha 60th ha Mulevhoguṱe uyu une wa tou vha ḓivha zwa kale khathihi na u pembelela vhuṱambo ha tshihumbudzo ha 150th ha Fakhaḽithi ya zwa milayo ya Yunivesithi ya Kapa. Ṱhalutshedzo yo vhalwa lwa u tou thoma Ṱhoho',
    vi: 'Gia đình đã đi du lịch đến bãi biển vào cuối tuần trước. Thời tiết thật hoàn hảo để bơi lội và tắm nắng suốt cả buổi chiều. Những đứa trẻ xây lâu đài cát trong khi cha mẹ thư giãn dưới bóng râm. Họ ăn cá tươi và uống nước dừa tại nhà hàng địa phương. Vào buổi tối, họ đi dọc theo bờ biển ngắm sao và lắng nghe tiếng sóng vỗ. Đó là một ngày tuyệt vời mà mọi người sẽ nhớ mãi.',
    wa: 'DÉCLARÅCION UNIVERSÈLE DÈS DREÛTS D L OME Preamble Il a stu ad mètu ne fèye po totes Qui l fondemint dè-l lîbèté, dè-l djustice èt dè-l påye tot-avå l monde, c èst l rik nohnance dè-l dignité qu èst l prôpe di tos lès-omes èt dès dreûts égâls qu ils ont èt qu on n èlzi pout mèskeure; Qui l fêt dè n in rik nohe ou dè foler ås pîds les dreûts d l ome ont k dû sacwants a rabahî èt brutålizer l s-ôtes d ine tèle manîre qui l consyince di l ûmanité ènn a stu révoltêye; Qui l pus grand èspwér dès djins, c èst l avén mint d on monde wice qui lès-omes sèront lîbes dè djåser èt dè creûre, tot-z-èstant d halés dè-l sogne èt dè-l mizére; Qui lès dreûts d l ome divèt-èsse ptotéjés d on rèdjime di dreût di téle dôrt qui l ome ènn arive nin a l rèvole disconte l abus dè pouvwér èt l assèrvih mint, fåte',
    wo: 'BATAAXAL GU MAG GI ËMB SAÑ-SAÑI DOOMI AADAMA Preamble Ñu jàpp te nangu ne sagu doomi aadama ak sañ-sañam yépp-dañu yam te kenn mënukóo jalgati, te lu lépp nekk na cës laay ci taxufeex ci mbirum àtte ak jàmm ci biir àdduna. Ñu jàpp ne ñakk xam ak soofantal sañ-sañi doomi aadama indi na aymusiba yu tar tax képp kuy dund fippu. Temano egsi na ba mu nekk ci doomi aadama ñu mën a wax, xalaat, ci seen coobare, bundxatal, nàkk dëddu leen. Ñu jàpp ne am na solo lool ñu aar sañ-sañi doomu aadama ak ay matukaay ci wàllu yoon; ngir doomu aadama moomu kenn du ko sonal, muy fippu ci nootaange ak lu koy bunduxatal. Ñu jàpp ne am na solo lool ñu góor-goorlu ba gën a rataxal jokkalante gi diggante xeet yi. Ñu jàpp ne ci bataaxal boobule mbootaayu xeet yi yeesalaat na ay pas-pasam jëme ko ci sañ-sani doomi',
    xh: 'INKCAZO‐JIKELELE NGEEMFANELO ZOLUNTU ISINGENISO Njengoko iimfanelo zesidima soluntu semvelo kunye neemfanelo zoluntu‐jikelele olungenakunikelwa olusisisekelo senkululeko, ubulungisa noxolo emhlabeni. Njengoko ukungananzi nokudelelwa kweemfanelo zoluntu ezingunobangela weziphumo zobukrwada ezithi zibangele ingcwangu kwisazela soluntu, kunye nesiqalo nokufika kwelizwe apho uluntu luza kuxhamla ukuthetha ngokukhululekileyo, inkolo nenkululeko engenaloyiko kunye neemfuno ezazisiweyo njengeminqweno yoluntu‐jikelele. Kwananjalo kubalulekile ke ngoko, ukuba umntu anganyanzeliswa ukufumana uncedo, okwetyeli lokugqibela, ukuchasa ubundlobongela nengcindezelo, kuba iimfanelo zesidima sobuntu mazikhuselwe ngolawulo lomthetho. Njengokuba kubalulekile ukukhuthaza kokwandiswa kobuhlobo nemvisiswano phaka',
    yo: 'Ìdílé ṣe ìrìn àjò lọ sí etíkun ní òpin ọ̀sẹ̀ tó kọjá. Ojú ọjọ́ dára fún odo àti gbigba oòrùn ní gbogbo ọ̀sán. Àwọn ọmọ kọ́ ilẹ̀ iyanrìn nígbà tí àwọn òbí ń sinmi ní iboji. Wọ́n jẹ ẹja tuntun wọ́n sì mu omi àgbọn ní ilé oúnjẹ àdúgbò. Ní alẹ́, wọ́n rin lẹ́bàá etíkun tí wọ́n ń wo ìràwọ̀ tí wọ́n sì ń fetí sí ariwo ìgbì omi. Ó jẹ́ ọjọ́ alárinwinniyìí tí gbogbo ènìyàn yóò rántí títí láé.',
    zh: '上周末全家去海滩旅行。整个下午的天气都非常适合游泳和享受阳光。孩子们在堆沙堡，而父母则在阴凉处休息。他们在当地餐厅吃了新鲜的鱼，喝了椰子水。晚上，他们沿着海岸散步，看着星星，听着海浪的声音。这是所有人都将永远铭记的美好一天。',
    zu: 'Umndeni wenze uhambo olusogadula olwandle ngempelasonto edlule. Isimo sezulu besihle ukuze ubhukude futhi ubheke ilanga ntambama yonke. Izingane zakha izinqaba zesihlabathi ngenkathi abazali bephumule emthunzini. Badla inhlanzi entsha futhi baphuza amanzi kakhukhunathi endaweni yokudlela yendawo. Kusihlwa, bahamba ngasogwini bebuka izinkanyezi futhi belalele umsindo wamagagasi. Kwakusukuzuhle abantu bonke abazosikhumbula unomphela.'
};

console.log('⚡ =================================================== ⚡');

console.log('     COMPLETE ISO 639-1 LANGUAGE DETECTION TEST        ');

console.log('⚡ =================================================== ⚡\n');

a.deepStrictEqual(e('Hola!!! 123 😀😀 hola hola spam spam!!!'), [ 'hola', 'spam' ]);

console.log('🧪 Tokenization regression test passed');

const o = getDatabaseInfo();

console.log(`📊 Database Info:`);

console.log(`   Type: ${o.type}`);

console.log(`   Languages: ${o.languages}`);

console.log(`   Total n-grams: ${o.ngrams.toLocaleString()}`);

console.log(`   Config: ${o.config.NGRAM_SIZES.join(', ')}-grams, top ${o.config.TOP_NGRAMS_PER_LANG} per language`);

console.log(`   Generated: ${o.generated}\n`);

(async () => {
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('📝 TEST RESULTS');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('ISO    Language                 Expected  Detected  Status  Accuracy  Time(ms)');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    let e = 0, o = 0;
    const t = [], r = [];
    // Test every ISO code that has a corpus sample.
        for (const a of Object.keys(i).sort()) {
        const l = n[a] || {
            name: a.toUpperCase()
        };
        const s = i[a];
        if (!s) continue;
        const u = performance.now();
        const d = detect(s);
        const m = performance.now() - u;
        o += m;
        const k = d.code === a;
        if (k) e++; else r.push({
            code: a,
            esperado: a,
            detectado: d.code,
            name: l.name
        });
        t.push({
            esperado: a,
            detectado: d.code,
            name: l.name,
            accuracy: d.accuracy,
            matches: d.matches,
            total: d.total,
            tiempo: m,
            ok: k
        });
        const g = k ? '✅' : '❌';
        const h = l.name.length > 20 ? l.name.substring(0, 17) + '...' : l.name.padEnd(20);
        console.log(`${g} ${a.toUpperCase().padEnd(4)} ${h}  ${a.toUpperCase().padEnd(7)} → ${d.code.toUpperCase().padEnd(7)}  ${(d.accuracy * 100).toFixed(1)}%    ${m.toFixed(2)}`);
    }
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
    // ────────────────────────────────────────────────────────────────────────────
    // API contract tests — every public function, option and the ESM/CLI surfaces
    // ────────────────────────────────────────────────────────────────────────────
        let l = 0, s = 0;
    async function u(a, e) {
        try {
            const n = e();
            if (n && typeof n.then === 'function') await n;
            l++;
            console.log(`   ✅ ${a}`);
        } catch (e) {
            s++;
            console.error(`   ❌ ${a}\n      ${e.message}`);
        }
    }
    console.log('\n🧪 API contract tests:');
    // — result shape / undecided —
        u('result shape (7 fields)', () => {
        const e = detect('Hola mundo');
        a.deepStrictEqual(Object.keys(e).sort(), [ 'accuracy', 'code', 'code2', 'detect', 'matches', 'name', 'total' ]);
        a.strictEqual(e.detect, e.code !== '');
        a.strictEqual(e.detect, true);
    });
    u('undecided input → neutral result', () => {
        const e = {
            code: '',
            code2: 'und',
            name: 'Undecided',
            accuracy: 0,
            matches: 0,
            total: 0,
            detect: false
        };
        for (const n of [ '', '   ', null, undefined, 123, {}, [] ]) {
            a.deepStrictEqual(detect(n), e);
        }
        a.deepStrictEqual(detect('', 3), []);
        a.strictEqual(detectAll('  ').length, 0);
    });
    // — detect: numeric limit / count —
        u('detect numeric limits', () => {
        a.ok(Array.isArray(detect('Hola mundo', 2)));
        a.strictEqual(detect('Hola mundo', 0).length, 0);
        a.ok(!Array.isArray(detect('Hola mundo', -1)));
        // invalid → single
                a.ok(!Array.isArray(detect('Hola mundo', 2.5)));
        // invalid → single
                a.ok(!Array.isArray(detect('Hola mundo', NaN)));
        // invalid → single
                const e = detect('Hola mundo', 3);
        a.ok(e.length <= 3);
        a.ok(e.every(a => a.detect && a.matches > 0));
    });
    u('detect { count } option', () => {
        a.ok(Array.isArray(detect('Hola mundo', {
            count: 2
        })));
        a.strictEqual(detect('Hola mundo', {
            count: 0
        }).length, 0);
        a.ok(!Array.isArray(detect('Hola mundo', {
            count: -1
        })));
        a.ok(!Array.isArray(detect('Hola mundo', {
            count: 1.5
        })));
    });
    // — options —
        u('detect allow', () => {
        const e = detect('Bonjour le monde', {
            allow: [ 'fr', 'en', 'es' ]
        });
        a.strictEqual(e.code, 'fr');
        a.ok([ 'fr', 'en', 'es' ].includes(e.code));
    });
    u('detect exclude', () => {
        a.notStrictEqual(detect('Hola mundo', {
            exclude: [ 'es' ]
        }).code, 'es');
        a.strictEqual(detect('Hola mundo', {
            exclude: [ 'es' ]
        }).detect, true);
    });
    u('detect minLen / minLength', () => {
        a.strictEqual(detect('hola', {
            minLen: 10
        }).detect, false);
        a.strictEqual(detect('hola', {
            minLength: 10
        }).detect, false);
        // alias
                a.strictEqual(detect('hola mundo', {
            minLen: 6
        }).detect, true);
    });
    u('null/undefined options do not throw', () => {
        a.strictEqual(detect('Hola mundo', null).code, detect('Hola mundo').code);
        a.ok(detectAll('Hola mundo', null).length >= 1);
        a.ok(detect('Hola mundo', undefined).code);
    });
    // — detectAll —
        u('detectAll returns ranked matches', () => {
        const e = detectAll('Hola mundo');
        a.ok(Array.isArray(e) && e.length > 0);
        a.strictEqual(e[0].code, 'es');
        a.ok(e.every(a => a.detect && a.matches > 0 && a.accuracy > 0));
    });
    u('detectAll allow/exclude', () => {
        const e = detectAll('Hola mundo', {
            allow: [ 'es', 'en' ]
        });
        a.ok(e.length >= 1 && e.every(a => [ 'es', 'en' ].includes(a.code)));
        a.ok(detectAll('Hola mundo', {
            exclude: [ 'es' ]
        }).every(a => a.code !== 'es'));
        a.strictEqual(detectAll('', {
            allow: [ 'es' ]
        }).length, 0);
    });
    // — metadata / lookups —
        u('getDatabaseInfo metadata', () => {
        const e = getDatabaseInfo();
        a.strictEqual(e.type, 'WEIGHTED_IDF');
        a.ok(Number.isInteger(e.dataVersion) && e.dataVersion > 0);
        a.strictEqual(e.languages, 115);
        a.ok(Number.isInteger(e.ngrams) && e.ngrams > 0);
        a.strictEqual(e.modelNgrams, e.ngrams);
        a.ok(Array.isArray(e.config.NGRAM_SIZES));
        a.ok(typeof e.generated === 'string' && e.generated.length > 0);
    });
    u('supportedLanguages', () => {
        const e = supportedLanguages();
        a.strictEqual(e.length, 115);
        a.ok(e.every(a => /^[a-z]{2}$/.test(a)));
        a.deepStrictEqual(e, [ ...e ].sort());
        for (const n of [ 'es', 'en', 'fr', 'de', 'zh', 'zu' ]) a.ok(e.includes(n), n);
    });
    u('languages', () => {
        const e = languages();
        a.strictEqual(e.length, 115);
        for (const n of e) {
            a.ok(/^[a-z]{2}$/.test(n.code), n.code);
            a.ok(/^[a-z]{3}$/.test(n.code2), n.code2);
            a.ok(n.name && typeof n.name === 'string', String(n.name));
        }
        a.strictEqual(e.find(a => a.code === 'es').name, 'Spanish');
    });
    u('hasLanguage', () => {
        a.strictEqual(hasLanguage('es'), true);
        a.strictEqual(hasLanguage('ES'), true);
        a.strictEqual(hasLanguage('spa'), true);
        a.strictEqual(hasLanguage('spanish'), true);
        a.strictEqual(hasLanguage('xyz'), false);
        a.strictEqual(hasLanguage('aa'), false);
        // ISO 639-1 but not in model
                a.strictEqual(hasLanguage(''), false);
        a.strictEqual(hasLanguage(null), false);
        a.strictEqual(hasLanguage(123), false);
    });
    u('code3', () => {
        a.strictEqual(code3('es'), 'spa');
        a.strictEqual(code3('ES'), 'spa');
        a.strictEqual(code3('spanish'), 'spa');
        a.strictEqual(code3('spa'), 'spa');
        a.strictEqual(code3('aa'), null);
        a.strictEqual(code3('xyz'), null);
        a.strictEqual(code3(''), null);
        a.strictEqual(code3(null), null);
    });
    u('name', () => {
        a.strictEqual(name('es'), 'Spanish');
        a.strictEqual(name('orm'), 'Oromo');
        a.strictEqual(name('xyz'), null);
        a.strictEqual(name(''), null);
        a.strictEqual(name(null), null);
    });
    // — packaging surface (ESM) — same public index.mjs exports via dynamic import
        await u('ESM surface parity (index.mjs)', async () => {
        const e = await (import('./index.mjs'));
        const n = [ 'code3', 'default', 'detect', 'detectAll', 'getDatabaseInfo', 'hasLanguage', 'languages', 'name', 'supportedLanguages' ];
        a.deepStrictEqual(Object.keys(e).sort(), n);
        a.deepStrictEqual(Object.keys(e.default).sort(), n.filter(a => a !== 'default'));
        a.strictEqual(e.detect('Hola mundo').code, 'es');
        a.strictEqual(e.detect('Hola mundo').detect, true);
        a.ok(e.detectAll('Hola mundo').length >= 1);
        a.strictEqual(e.languages().length, 115);
        a.strictEqual(e.code3('es'), 'spa');
        a.strictEqual(e.name('es'), 'Spanish');
        a.strictEqual(e.hasLanguage('es'), true);
    });
    console.log(`\n🧪 API contract: ${l}/${l + s} passed\n`);
    const d = t.length > 0 ? e / t.length * 100 : 0;
    const m = t.length > 0 ? o / t.length : 0;
    console.log('════════════════════════════════════════════════════════════');
    console.log('📊 FINAL SUMMARY');
    console.log('════════════════════════════════════════════════════════════');
    console.log(`✅ Correct:      ${e}/${t.length} (${d.toFixed(1)}%)`);
    console.log(`⏱️  Total time:   ${o.toFixed(2)} ms`);
    console.log(`⚡ Average:      ${m.toFixed(2)} ms per text`);
    console.log(`📋 Languages tested: ${t.length} out of ${Object.keys(n).length} total ISO codes`);
    if (r.length > 0 || s > 0) {
        console.log(`\n❌ FAILED — ${r.length} detection mismatch(es), ${s} API contract test(s) failed.`);
        if (r.length > 0) {
            console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
            r.forEach(a => console.log(`   ${a.code.toUpperCase()} (${a.name}) → ${a.detectado.toUpperCase()}`));
        }
        process.exit(1);
    } else {
        console.log(`\n🎉 PERFECT! All languages detected, all API contract tests passed.`);
    }
    console.log(`\n📈 ACCURACY DISTRIBUTION:`);
    const k = t.map(a => a.accuracy);
    const g = k.filter(a => a === 1).length;
    const h = k.filter(a => a >= .9 && a < 1).length;
    const c = k.filter(a => a >= .7 && a < .9).length;
    const b = k.filter(a => a < .7).length;
    console.log(`   100%:       ${g} languages`);
    console.log(`   90-99%:     ${h} languages`);
    console.log(`   70-89%:     ${c} languages`);
    console.log(`   <70%:       ${b} languages`);
})();